version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - security
      - npm
    groups:
      npm-compatible-patches:
        update-types:
          - patch
      npm-compatible-minors:
        update-types:
          - minor
        exclude-patterns:
          - tailwindcss
    ignore:
      - dependency-name: tailwindcss
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - security
      - github-actions
    groups:
      actions-compatible-patches:
        update-types:
          - patch
      actions-compatible-minors:
        update-types:
          - minor
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
