import { CheckCircle2, Eye, Building2 } from 'lucide-react';
import { useState } from 'react';
import { useProblemTimeline } from '../../hooks/useProblemTimeline';
import { ProblemTimelineRepository } from '../../repositories/problemTimeline';
import { problemStatuses, type ProblemStatus } from '../../types/problemTimeline';

export function ProblemTimeline({problemId,canPublish,organization,onStatusChange}:{problemId:string;canPublish:boolean;organization:string;onStatusChange?:(status:ProblemStatus)=>void}) {
 const {events,loading,error,reload}=useProblemTimeline(problemId); const [open,setOpen]=useState(false); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [status,setStatus]=useState<ProblemStatus|''>(''); const [feedback,setFeedback]=useState(''); const [saving,setSaving]=useState(false);
 const publish=async(e:{preventDefault():void})=>{e.preventDefault();if(!ProblemTimelineRepository)return setFeedback('Atualizações oficiais exigem conexão com o Supabase.');setSaving(true);const result=await ProblemTimelineRepository.publishOfficialUpdate(problemId,title,description,organization,status||undefined);setSaving(false);if(!result.ok)return setFeedback(result.message);setTitle('');setDescription('');setStatus('');setOpen(false);setFeedback('Atualização publicada.');if(status)onStatusChange?.(status);await reload();};
 return <section className="rounded-[2rem] border border-line bg-white p-6 shadow-sm" aria-labelledby="timeline-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="timeline-title" className="text-2xl font-semibold">Linha do tempo</h2>{canPublish&&<button className="rounded-full bg-teal-700 px-4 py-2 text-sm font-semibold text-white focus:ring-2 focus:ring-teal-400" onClick={()=>setOpen(v=>!v)}>Nova atualização</button>}</div>
 {open&&<form onSubmit={publish} className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4" aria-label="Publicar atualização oficial"><label className="grid gap-1 text-sm font-medium">Título<input required maxLength={160} className="rounded-xl border border-line px-3 py-2" value={title} onChange={(e: { target: { value: string } })=>setTitle(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Descrição<textarea maxLength={5000} className="min-h-24 rounded-xl border border-line px-3 py-2" value={description} onChange={(e: { target: { value: string } })=>setDescription(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Status opcional<select className="rounded-xl border border-line px-3 py-2" value={status} onChange={(e: { target: { value: string } })=>setStatus(e.target.value as ProblemStatus|'')}><option value="">Não alterar</option>{problemStatuses.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={saving} className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving?'Publicando...':'Publicar'}</button></form>}
 {feedback&&<p role="status" className="mt-3 text-sm font-medium">{feedback}</p>}{loading?<p className="mt-5 text-muted">Carregando linha do tempo...</p>:error?<p role="alert" className="mt-5 text-red-700">{error}</p>:events.length===0?<p className="mt-5 text-muted">Nenhum evento registrado.</p>:<ol className="mt-6" aria-label="Evolução pública do problema">{events.map((event,index)=>{const done=event.statusAfter==='Resolvido'||event.eventType==='problem.closed';return <li key={event.id} tabIndex={0} className="group relative grid grid-cols-[2rem_1fr] gap-3 pb-7 outline-none focus-visible:ring-2 focus-visible:ring-teal-400">{index<events.length-1&&<span aria-hidden className="absolute left-[15px] top-7 h-[calc(100%-1.25rem)] w-px bg-slate-300"/>}<span className="relative z-10 mt-0.5 text-teal-700">{done?<CheckCircle2 aria-hidden/>:event.official?<Building2 aria-hidden/>:<Eye aria-hidden/>}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{event.title}</h3>{event.official&&<span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-semibold text-teal-800">Atualização oficial</span>}</div>{event.description&&<p className="mt-1 whitespace-pre-wrap text-sm text-muted">{event.description}</p>}<p className="mt-2 text-xs text-slate-500">{event.organizationName||event.actorName} · {new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.createdAt))}</p></div></li>;})}</ol>}</section>;
}
