import { useEffect, useRef, useState, type FormEvent } from 'react';
import { FileWarning } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { ContentReportRepository } from '../../repositories/contentReports';
import { contentReportReasons, type ContentReportReason, type ContentReportTarget } from '../../types/contentReport';
import { useTranslation } from '../../i18n/I18nProvider';
import { saveAuthReturnTo } from '../auth/authReturnTo';
export function ReportContentDialog({targetType,targetId,onLoginRequired}:{targetType:ContentReportTarget;targetId:string;onLoginRequired:()=>void}){
 const {user}=useAuth();const {t}=useTranslation();const [open,setOpen]=useState(false);const [reason,setReason]=useState<ContentReportReason|''>('');const [description,setDescription]=useState('');const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');const [message,setMessage]=useState('');const trigger=useRef<HTMLButtonElement|null>(null);const select=useRef<HTMLSelectElement|null>(null);
 useEffect(()=>{if(open)select.current?.focus();},[open]);
 const close=()=>{setOpen(false);trigger.current?.focus();};
 const start=()=>{if(!user){saveAuthReturnTo(undefined,true);onLoginRequired();return;}setOpen(true);setState('idle');setMessage('');};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(state==='sending'||!reason||(reason==='other'&&!description.trim()))return;setState('sending');const result=await ContentReportRepository?.create(targetType,targetId,reason,description);if(result?.ok){setState('success');setMessage(t('reports.sent'));}else{setState('error');setMessage(result?.message??t('reports.unavailable'));}};
 return <><button ref={trigger} type="button" onClick={start} className="inline-flex items-center gap-2 rounded-full border border-amber-300 px-5 py-3 text-sm font-semibold text-amber-800"><FileWarning size={16}/>{t('reports.action')}</button>{open&&<div role="dialog" aria-modal="true" aria-labelledby="report-title" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" onKeyDown={(e: { key: string })=>{if(e.key==='Escape')close();}}><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-xl"><h2 id="report-title" className="text-2xl font-semibold">{t('reports.title')}</h2><p className="mt-2 text-sm text-muted">{t('reports.description')}</p><label htmlFor={`report-reason-${targetId}`} className="mt-5 block font-semibold">{t('reports.reason')}</label><select ref={select} id={`report-reason-${targetId}`} required value={reason} onChange={(e: { target: { value: string } })=>setReason(e.target.value as ContentReportReason)} className="mt-2 w-full rounded-xl border p-3"><option value="">{t('reports.selectReason')}</option>{contentReportReasons.map(item=><option key={item} value={item}>{t(`reports.reason.${item}` as never)}</option>)}</select><label htmlFor={`report-description-${targetId}`} className="mt-4 block font-semibold">{t('reports.optionalDetails')}</label><textarea id={`report-description-${targetId}`} maxLength={1000} required={reason==='other'} value={description} onChange={(e: { target: { value: string } })=>setDescription(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border p-3"/><p className="text-right text-xs text-muted">{description.length}/1000</p>{message&&<p role="status" className={`mt-3 rounded-xl p-3 text-sm ${state==='error'?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{message}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-full border px-5 py-2">{t('common.cancel')}</button>{state!=='success'&&<button disabled={state==='sending'||!reason||(reason==='other'&&!description.trim())} className="rounded-full bg-amber-700 px-5 py-2 font-semibold text-white disabled:opacity-50">{state==='sending'?t('reports.sending'):t('reports.submit')}</button>}</div></form></div>}</>;
}
