import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { sanitizeLogContext } from '../lib/logger.ts';
import { checkDatabaseHealth, EXPECTED_SCHEMA_VERSION } from './systemHealth.ts';
import { runDatabaseCheck } from '../../scripts/checkDatabase.ts';
import { baselineSummary, parseMigrationList, runMigrationBaselineCheck, validateMigrationBaseline } from '../../scripts/checkMigrationBaseline.ts';

type Failure = { message: string; code?: string };
const baseChecks = () => ['database','schema_version','required_rpcs','required_columns'].map((name) => ({ name, status:'ok' as const, message:'OK', latency_ms:1 }));
function client(options: { checks?: ReturnType<typeof baseChecks>; version?: string; rpcError?: Failure; authError?: Failure; storageError?: Failure; malformed?: boolean } = {}) {
  return {
    rpc: async () => options.rpcError ? {data:null,error:options.rpcError} : {data:options.malformed ? {ok:true} : {ok:true,schema_version:options.version ?? EXPECTED_SCHEMA_VERSION,checked_at:new Date().toISOString(),checks:options.checks ?? baseChecks()},error:null},
    auth: { getUser: async () => ({data:{user:null},error:options.authError ?? null}) },
    storage: { listBuckets: async () => ({data:[],error:options.storageError ?? null}) },
  };
}

test('Supabase não configurado',async()=>{const result=await checkDatabaseHealth(null);assert.equal(result.ok,false);assert.equal(result.checks[0]?.name,'database');});
test('health saudável contém auth, storage e latência',async()=>{const result=await checkDatabaseHealth(client() as never);assert.equal(result.ok,true);assert.ok(result.checks.some((c)=>c.name==='auth'));assert.ok(result.checks.some((c)=>c.name==='storage'));assert.equal(typeof result.checks.find((c)=>c.name==='response_time')?.latency_ms,'number');});
for (const [label,name,message] of [['RPC ausente','required_rpcs','RPC ausente'],['assinatura incompatível','required_rpcs','Assinatura incompatível'],['coluna ausente','required_columns','Coluna ausente']] as const) test(label,async()=>{const checks=baseChecks();Object.assign(checks.find((c)=>c.name===name)!,{status:'error',message});assert.equal((await checkDatabaseHealth(client({checks}) as never)).ok,false);});
test('schema incompatível é rejeitado com mensagem pública',async()=>{const result=await checkDatabaseHealth(client({version:'25.1.0'}) as never);assert.equal(result.ok,false);assert.equal(result.checks.find((c)=>c.name==='schema_version')?.message,'Versão do banco incompatível com esta versão da aplicação.');});
test('Auth indisponível é sanitizado',async()=>{const result=await checkDatabaseHealth(client({authError:{message:'JWT secreto'}}) as never);assert.equal(result.checks.find((c)=>c.name==='auth')?.message,'Não foi possível validar o serviço de autenticação.');});
test('Storage indisponível é sanitizado',async()=>{const result=await checkDatabaseHealth(client({storageError:{message:'bucket interno'}}) as never);assert.equal(result.checks.find((c)=>c.name==='storage')?.message,'Não foi possível validar o serviço de armazenamento.');});
test('erro técnico não chega ao resultado',async()=>{const result=await checkDatabaseHealth(client({rpcError:{message:'column source_metadata does not exist',code:'42703'}}) as never);assert.equal(JSON.stringify(result).includes('source_metadata'),false);});
test('resposta RPC malformada falha de forma segura',async()=>{assert.equal((await checkDatabaseHealth(client({malformed:true}) as never)).ok,false);});
test('logger remove segredos recursivamente',()=>{assert.deepEqual(sanitizeLogContext({token:'x',nested:{authorization:'y'},safe:'ok'}),{token:'[REDACTED]',nested:{authorization:'[REDACTED]'},safe:'ok'});});
test('script de CI retorna exit code de erro sem configuração',async()=>{assert.equal(await runDatabaseCheck({}),1);});
test('script exige service role e não aceita access token da CLI como JWT',async()=>{assert.equal(await runDatabaseCheck({SUPABASE_URL:'https://example.invalid',SUPABASE_ACCESS_TOKEN:'management'}),1);});
test('check de deploy usa somente endpoints estáveis e aceita HTTP 200',async()=>{const original=globalThis.fetch;const urls:string[]=[];globalThis.fetch=(async(url: string|URL|Request)=>{urls.push(String(url));return {status:200} as Response;}) as typeof fetch;try{assert.equal(await runDatabaseCheck({SUPABASE_URL:'https://example.invalid/',SUPABASE_SERVICE_ROLE_KEY:'server-only'}),0);assert.deepEqual(urls.sort(),['https://example.invalid/auth/v1/settings','https://example.invalid/rest/v1/','https://example.invalid/storage/v1/bucket'].sort());}finally{globalThis.fetch=original;}});
test('check de deploy falha para resposta inesperada ou erro de rede e não vaza segredo',async()=>{const originalFetch=globalThis.fetch;const originalError=console.error;const originalLog=console.log;let output='';let calls=0;globalThis.fetch=(async()=>{calls++;if(calls===1)return {status:503} as Response;throw new Error('network token=server-only');}) as typeof fetch;console.error=(value?:unknown)=>{output+=String(value);};console.log=(value?:unknown)=>{output+=String(value);};try{assert.equal(await runDatabaseCheck({SUPABASE_URL:'https://secret-host.invalid',SUPABASE_SERVICE_ROLE_KEY:'server-only'}),1);assert.equal(output.includes('server-only'),false);assert.equal(output.includes('secret-host'),false);}finally{globalThis.fetch=originalFetch;console.error=originalError;console.log=originalLog;}});
test('check de deploy não contém RPC de diagnóstico',()=>{const source=readFileSync(new URL('../../scripts/checkDatabase.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/get_system_health|audit_legacy_schema|\/rest\/v1\/rpc\//);});
test('visitante em rota administrativa é redirecionado ao login',()=>{const source=readFileSync(new URL('../components/admin/AdminRoute.tsx',import.meta.url),'utf8');assert.match(source,/!isLoading && !isAuthenticated\) onLoginRequired\(\)/);assert.match(source,/if \(!isAuthenticated\) return null/);});
test('usuário comum recebe 403 e somente admin possui acesso administrativo',()=>{const route=readFileSync(new URL('../components/admin/AdminRoute.tsx',import.meta.url),'utf8');const permissions=readFileSync(new URL('../hooks/usePermissions.ts',import.meta.url),'utf8');assert.match(route,/if \(!isAdmin\) return <ForbiddenPage/);assert.match(route,/Erro 403/);assert.match(permissions,/const isAdmin = hasRole\(user, \['admin'\]\)/);assert.match(permissions,/canAccessAdmin: isAdmin/);});
test('administrador visualiza o dashboard administrativo',()=>{const app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');const dashboard=readFileSync(new URL('../pages/AdminDashboard.tsx',import.meta.url),'utf8');assert.match(app,/<AdminRoute[^>]*isAdmin=\{permissions\.canAccessAdmin\}/);for(const section of ['Usuários','Problemas','Soluções','Comentários','Denúncias','Auditoria','Sistema']) assert.match(dashboard,new RegExp(`title: '${section}'`));});
test('funcionalidades administrativas legadas permanecem renderizáveis nas rotas administrativas',()=>{const app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');const legacy=readFileSync(new URL('../pages/LegacyAdminPanel.tsx',import.meta.url),'utf8');assert.match(app,/<AdminUsers onBack=/);for(const tab of ['comments','audit','contributions']) assert.match(app,new RegExp(`<AdminPanel initialTab=\\"${tab}\\"`));for(const feature of ['ContributionDiff','CommentRepository','AuditPanel','RoleManager','Histórico da moderação de comentários']) assert.match(legacy,new RegExp(feature));});
test('mapa usa mensagens amigáveis nas três operações',()=>{const source=readFileSync(new URL('../repositories/map/MapRepository.ts',import.meta.url),'utf8');assert.match(source,/Não foi possível atualizar o mapa/);assert.match(source,/Não foi possível carregar o resumo/);assert.match(source,/Não foi possível carregar a localização/);});
test('migration autoriza service role e admin autenticado, negando usuário comum e anon',()=>{const sql=readFileSync(new URL('../../supabase/migrations/20260717260000_sprint26_system_health.sql',import.meta.url),'utf8');assert.match(sql,/auth\.role\(\) is distinct from 'service_role' and not coalesce\(public\.is_admin\(\), false\)/);assert.match(sql,/grant execute.*authenticated/);assert.match(sql,/grant execute.*service_role/);assert.doesNotMatch(sql,/grant execute.*anon/);});
test('histórico remoto ausente falha',()=>{assert.ok(validateMigrationBaseline(parseMigrationList('20260717250000 | |')).some((error)=>error.includes('Histórico remoto')));});
test('migration 25 ausente no remoto falha',()=>{const state=parseMigrationList('20260717250000 | |\n20260717251000 | 20260717251000 |\n20260717260000 | |');assert.ok(validateMigrationBaseline(state).some((error)=>error.includes('20260717250000')));});
test('migration 25.1 ausente no remoto falha',()=>{const state=parseMigrationList('20260717250000 | 20260717250000 |\n20260717251000 | |\n20260717260000 | |');assert.ok(validateMigrationBaseline(state).some((error)=>error.includes('20260717251000')));});
test('cenário legado exige reconciliação registrada antes do baseline',()=>{const legacy=parseMigrationList('20260717250000 | 20260717250000 |\n20260717251000 | 20260717251000 |\n20260717259000 | |');assert.ok(validateMigrationBaseline(legacy).some((error)=>error.includes('Cenário legado')));const reconciled=parseMigrationList('20260717250000 | 20260717250000 |\n20260717251000 | 20260717251000 |\n20260717259000 | 20260717259000 |\n20260717260000 | |');assert.deepEqual(validateMigrationBaseline(reconciled),[]);assert.match(baselineSummary(reconciled,[]),/Sprint 26: pendente/);});
test('check de baseline retorna erro e saída não inclui stdout técnico',()=>{const original=console.error;let output='';console.error=(message?:unknown)=>{output+=String(message);};try{assert.equal(runMigrationBaselineCheck(()=>({status:1,stdout:'password=secret'})),1);assert.equal(output.includes('password=secret'),false);}finally{console.error=original;}});
test('workflow principal mantém migrations e health como gates de deploy',()=>{const workflow=readFileSync(new URL('../../.github/workflows/deploy.yml',import.meta.url),'utf8');const push=workflow.indexOf('npx --yes supabase@2.39.2 db push');const health=workflow.indexOf('npm run check:database');const upload=workflow.indexOf('uses: actions/upload-pages-artifact');assert.ok(push>0&&health>push&&upload>health);assert.match(workflow,/migrate-and-health:\n    if: github\.event_name == 'push'/);assert.match(workflow,/deploy:[\s\S]*needs: migrate-and-health/);assert.match(workflow,/run: npm ci/);assert.doesNotMatch(workflow,/audit_legacy_schema|get_system_health|\/rest\/v1\/rpc\/|continue-on-error|run:\s+.*migration repair/);assert.doesNotMatch(workflow,/VITE_SUPABASE_(ACCESS_TOKEN|SERVICE_ROLE_KEY|DB_PASSWORD)/);});
test('production preflight valida o mesmo banco sem deploy nem push real',()=>{const workflow=readFileSync(new URL('../../.github/workflows/production-preflight.yml',import.meta.url),'utf8');assert.match(workflow,/workflow_dispatch:/);assert.match(workflow,/ref: \$\{\{ inputs\.ref \}\}/);assert.match(workflow,/run: npm ci/);assert.match(workflow,/run: npm test/);assert.match(workflow,/run: npm run build/);assert.match(workflow,/run: npm run test:pending-migrations/);assert.match(workflow,/migration list --linked/);assert.match(workflow,/db push --dry-run/);assert.match(workflow,/npm run check:database/);assert.doesNotMatch(workflow,/actions\/(?:deploy-pages|upload-pages-artifact)|continue-on-error|migration repair|audit_legacy_schema|get_system_health|\/rest\/v1\/rpc\//);});
test('jobs that run Node checks install dependencies first',()=>{for(const path of ['../../.github/workflows/deploy.yml','../../.github/workflows/production-preflight.yml']){const workflow=readFileSync(new URL(path,import.meta.url),'utf8');for(const command of ['npm run check:database','npm run test:pending-migrations']) {const commandAt=workflow.indexOf(command);assert.ok(commandAt>=0&&workflow.lastIndexOf('run: npm ci',commandAt)>=0,`${command} must follow npm ci in ${path}`);}}});
