import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { sanitizeLogContext } from '../lib/logger.ts';
import { checkDatabaseHealth, EXPECTED_SCHEMA_VERSION } from './systemHealth.ts';
import { runDatabaseCheck } from '../../scripts/checkDatabase.ts';
import { baselineSummary, parseMigrationList, runMigrationBaselineCheck, validateMigrationBaseline } from '../../scripts/checkMigrationBaseline.ts';

type Failure = { message: string; code?: string };
const baseChecks = () => ['database','schema_version','required_rpcs','required_columns'].map((name) => ({ name, status:'ok' as const, message:'OK', latency_ms:1 }));
function client(options: { checks?: ReturnType<typeof baseChecks>; version?: string; rpcError?: Failure; authError?: Failure; storageError?: Failure; malformed?: boolean } = {}) {
  return {
    rpc: async () => options.rpcError ? {data:null,error:options.rpcError} : {data:options.malformed ? {ok:true} : {ok:true,schema_version:options.version ?? EXPECTED_SCHEMA_VERSION,checked_at:new Date().toISOString(),checks:options.checks ?? baseChecks()},error:null},
    auth: { getUser: async () => ({data:{user:null},error:options.authError ?? null}) },
    storage: { listBuckets: async () => ({data:[],error:options.storageError ?? null}) },
  };
}

test('Supabase não configurado',async()=>{const result=await checkDatabaseHealth(null);assert.equal(result.ok,false);assert.equal(result.checks[0]?.name,'database');});
test('health saudável contém auth, storage e latência',async()=>{const result=await checkDatabaseHealth(client() as never);assert.equal(result.ok,true);assert.ok(result.checks.some((c)=>c.name==='auth'));assert.ok(result.checks.some((c)=>c.name==='storage'));assert.equal(typeof result.checks.find((c)=>c.name==='response_time')?.latency_ms,'number');});
for (const [label,name,message] of [['RPC ausente','required_rpcs','RPC ausente'],['assinatura incompatível','required_rpcs','Assinatura incompatível'],['coluna ausente','required_columns','Coluna ausente']] as const) test(label,async()=>{const checks=baseChecks();Object.assign(checks.find((c)=>c.name===name)!,{status:'error',message});assert.equal((await checkDatabaseHealth(client({checks}) as never)).ok,false);});
test('schema incompatível é rejeitado com mensagem pública',async()=>{const result=await checkDatabaseHealth(client({version:'25.1.0'}) as never);assert.equal(result.ok,false);assert.equal(result.checks.find((c)=>c.name==='schema_version')?.message,'Versão do banco incompatível com esta versão da aplicação.');});
test('Auth indisponível é sanitizado',async()=>{const result=await checkDatabaseHealth(client({authError:{message:'JWT secreto'}}) as never);assert.equal(result.checks.find((c)=>c.name==='auth')?.message,'Não foi possível validar o serviço de autenticação.');});
test('Storage indisponível é sanitizado',async()=>{const result=await checkDatabaseHealth(client({storageError:{message:'bucket interno'}}) as never);assert.equal(result.checks.find((c)=>c.name==='storage')?.message,'Não foi possível validar o serviço de armazenamento.');});
test('erro técnico não chega ao resultado',async()=>{const result=await checkDatabaseHealth(client({rpcError:{message:'column source_metadata does not exist',code:'42703'}}) as never);assert.equal(JSON.stringify(result).includes('source_metadata'),false);});
test('resposta RPC malformada falha de forma segura',async()=>{assert.equal((await checkDatabaseHealth(client({malformed:true}) as never)).ok,false);});
test('logger remove segredos recursivamente',()=>{assert.deepEqual(sanitizeLogContext({token:'x',nested:{authorization:'y'},safe:'ok'}),{token:'[REDACTED]',nested:{authorization:'[REDACTED]'},safe:'ok'});});
test('script de CI retorna exit code de erro sem configuração',async()=>{assert.equal(await runDatabaseCheck({}),1);});
test('script exige service role e não aceita access token da CLI como JWT',async()=>{assert.equal(await runDatabaseCheck({SUPABASE_URL:'https://example.invalid',SUPABASE_ACCESS_TOKEN:'management'}),1);});
test('script de CI falha quando health.ok é false',async()=>{const original=globalThis.fetch;globalThis.fetch=(async(url: string|URL|Request)=>({ok:true,status:200,json:async()=>String(url).includes('/rpc/')?{ok:false,schema_version:EXPECTED_SCHEMA_VERSION,checked_at:new Date().toISOString(),checks:baseChecks().map((check)=>check.name==='required_rpcs'?{...check,status:'error',message:'RPC ausente'}:check)}:{}})) as typeof fetch;try{assert.equal(await runDatabaseCheck({SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'server-only'}),1);}finally{globalThis.fetch=original;}});
test('visitante em rota administrativa é redirecionado ao login',()=>{const source=readFileSync(new URL('../components/admin/AdminRoute.tsx',import.meta.url),'utf8');assert.match(source,/!isLoading && !isAuthenticated\) onLoginRequired\(\)/);assert.match(source,/if \(!isAuthenticated\) return null/);});
test('usuário comum recebe 403 e somente admin possui acesso administrativo',()=>{const route=readFileSync(new URL('../components/admin/AdminRoute.tsx',import.meta.url),'utf8');const permissions=readFileSync(new URL('../hooks/usePermissions.ts',import.meta.url),'utf8');assert.match(route,/if \(!isAdmin\) return <ForbiddenPage/);assert.match(route,/Erro 403/);assert.match(permissions,/const isAdmin = hasRole\(user, \['admin'\]\)/);assert.match(permissions,/canAccessAdmin: isAdmin/);});
test('administrador visualiza o dashboard administrativo',()=>{const app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');const dashboard=readFileSync(new URL('../pages/AdminDashboard.tsx',import.meta.url),'utf8');assert.match(app,/<AdminRoute[^>]*isAdmin=\{permissions\.canAccessAdmin\}/);for(const section of ['Usuários','Problemas','Soluções','Comentários','Denúncias','Auditoria','Sistema']) assert.match(dashboard,new RegExp(`title: '${section}'`));});
test('funcionalidades administrativas legadas permanecem renderizáveis nas rotas administrativas',()=>{const app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');const legacy=readFileSync(new URL('../pages/LegacyAdminPanel.tsx',import.meta.url),'utf8');for(const tab of ['roles','comments','audit','contributions']) assert.match(app,new RegExp(`<AdminPanel initialTab=\\"${tab}\\"`));for(const feature of ['ContributionDiff','CommentRepository','AuditPanel','RoleManager','Histórico da moderação de comentários']) assert.match(legacy,new RegExp(feature));});
test('mapa usa mensagens amigáveis nas três operações',()=>{const source=readFileSync(new URL('../repositories/map/MapRepository.ts',import.meta.url),'utf8');assert.match(source,/Não foi possível atualizar o mapa/);assert.match(source,/Não foi possível carregar o resumo/);assert.match(source,/Não foi possível carregar a localização/);});
test('migration autoriza service role e admin autenticado, negando usuário comum e anon',()=>{const sql=readFileSync(new URL('../../supabase/migrations/20260717260000_sprint26_system_health.sql',import.meta.url),'utf8');assert.match(sql,/auth\.role\(\) is distinct from 'service_role' and not coalesce\(public\.is_admin\(\), false\)/);assert.match(sql,/grant execute.*authenticated/);assert.match(sql,/grant execute.*service_role/);assert.doesNotMatch(sql,/grant execute.*anon/);});
test('histórico remoto ausente falha',()=>{assert.ok(validateMigrationBaseline(parseMigrationList('20260717250000 | |')).some((error)=>error.includes('Histórico remoto')));});
test('migration 25 ausente no remoto falha',()=>{const state=parseMigrationList('20260717250000 | |\n20260717251000 | 20260717251000 |\n20260717260000 | |');assert.ok(validateMigrationBaseline(state).some((error)=>error.includes('20260717250000')));});
test('migration 25.1 ausente no remoto falha',()=>{const state=parseMigrationList('20260717250000 | 20260717250000 |\n20260717251000 | |\n20260717260000 | |');assert.ok(validateMigrationBaseline(state).some((error)=>error.includes('20260717251000')));});
test('cenário legado exige reconciliação registrada antes do baseline',()=>{const legacy=parseMigrationList('20260717250000 | 20260717250000 |\n20260717251000 | 20260717251000 |\n20260717259000 | |');assert.ok(validateMigrationBaseline(legacy).some((error)=>error.includes('Cenário legado')));const reconciled=parseMigrationList('20260717250000 | 20260717250000 |\n20260717251000 | 20260717251000 |\n20260717259000 | 20260717259000 |\n20260717260000 | |');assert.deepEqual(validateMigrationBaseline(reconciled),[]);assert.match(baselineSummary(reconciled,[]),/Sprint 26: pendente/);});
test('check de baseline retorna erro e saída não inclui stdout técnico',()=>{const original=console.error;let output='';console.error=(message?:unknown)=>{output+=String(message);};try{assert.equal(runMigrationBaselineCheck(()=>({status:1,stdout:'password=secret'})),1);assert.equal(output.includes('password=secret'),false);}finally{console.error=original;}});
test('workflow audita depois do baseline sem push ou repair automáticos',()=>{const workflow=readFileSync(new URL('../../.github/workflows/deploy.yml',import.meta.url),'utf8');const baseline=workflow.indexOf('Check migration baseline');const audit=workflow.indexOf('Audit production schema');const health=workflow.indexOf('Validate production database health');assert.ok(baseline>0&&audit>baseline&&health>audit);assert.doesNotMatch(workflow,/run:\s+.*migration repair/);assert.match(workflow,/run:\s+.*\bdb push\b/);assert.match(workflow,/migrate-and-health:\n    if: github\.event_name == 'push'/);assert.match(workflow,/deploy:[\s\S]*needs: migrate-and-health/);assert.doesNotMatch(workflow,/VITE_SUPABASE_(ACCESS_TOKEN|SERVICE_ROLE_KEY|DB_PASSWORD)/);});
