import { useState, type ChangeEvent } from 'react';
import { useTaxonomyProposals } from '../../hooks/useTaxonomy';
import type { TaxonomyKind, TaxonomyProposal, TaxonomyScope } from '../../types/taxonomy';
import { useTranslation } from '../../i18n/I18nProvider';
import { formatDateTime } from '../../i18n/format';
import type { TranslationKey } from '../../i18n/resources';
const kindKeys: Record<TaxonomyKind, TranslationKey> = { category:'taxonomy.kind.category', tag:'taxonomy.kind.tag' };
const scopeKeys: Record<TaxonomyScope, TranslationKey> = { problem:'taxonomy.scope.problem', solution:'taxonomy.scope.solution', both:'taxonomy.scope.both' };
export function TaxonomyProposalQueue() {
  const { locale, t } = useTranslation(); const hook = useTaxonomyProposals('queue'), [selected, setSelected] = useState<TaxonomyProposal | null>(null), [decision, setDecision] = useState<'approved' | 'rejected'>('approved'), [reason, setReason] = useState('');
  const confirm = async () => { if (!selected) return; const result = await hook.review(selected.id, decision, reason); if (result.ok) { setSelected(null); setReason(''); } };
  return <section className="space-y-3"><h2>{t('taxonomy.title')}</h2><p aria-live="polite">{hook.message}</p>{hook.loading ? <p>{t('taxonomy.queueLoading')}</p> : hook.error ? <p role="alert">{hook.error} <button onClick={() => void hook.retry()}>{t('common.retry')}</button></p> : hook.items.length ? hook.items.map((item) => <article key={item.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{item.proposedName}</h3><dl className="grid gap-1 text-sm"><div><dt className="inline font-semibold">{t('taxonomy.type')} </dt><dd className="inline">{t(kindKeys[item.kind])}</dd></div><div><dt className="inline font-semibold">{t('taxonomy.scope')} </dt><dd className="inline">{t(scopeKeys[item.scope])}</dd></div><div><dt className="inline font-semibold">{t('taxonomy.author')} </dt><dd className="inline">{item.authorId}</dd></div><div><dt className="inline font-semibold">{t('taxonomy.proposedAt')} </dt><dd className="inline">{formatDateTime(item.createdAt, locale)}</dd></div><div><dt className="inline font-semibold">{t('contributions.justification')} </dt><dd className="inline">{item.justification}</dd></div></dl><button onClick={() => { setSelected(item); setDecision('approved'); }}>{t('taxonomy.review')}</button></article>) : <p>{t('taxonomy.pendingEmpty')}</p>}{selected && <div role="dialog" aria-modal="true" aria-labelledby="taxonomy-review-title" className="rounded-2xl border bg-white p-4"><h3 id="taxonomy-review-title">{t('taxonomy.reviewTitle', { name: selected.proposedName })}</h3><label><input type="radio" checked={decision === 'approved'} onChange={() => setDecision('approved')} /> {t('taxonomy.approve')}</label><label><input type="radio" checked={decision === 'rejected'} onChange={() => setDecision('rejected')} /> {t('taxonomy.reject')}</label><label className="grid">{t('taxonomy.reason')}<textarea value={reason} required={decision === 'rejected'} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => setReason(event.target.value)} className="border p-2" /></label><button disabled={hook.submitting || decision === 'rejected' && reason.trim().length < 3} onClick={() => void confirm()}>{t('common.confirm')}</button><button onClick={() => setSelected(null)}>{t('common.cancel')}</button></div>}</section>;
}
