import type { AdminUserRecord } from '../../repositories/adminUsers';
import { useTranslation } from '../../i18n/I18nProvider';
import { userRoleKeys } from '../../i18n/presentation';

interface Props { users: AdminUserRecord[]; onChangeRole: (user: AdminUserRecord, source: HTMLButtonElement) => void; }
function Avatar({ name }: { name: string }) { return <span aria-hidden="true" className="inline-flex size-10 shrink-0 items-center justify-center rounded-full bg-teal-100 font-semibold text-teal-800 dark:bg-teal-950 dark:text-teal-200">{name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'U'}</span>; }
function RoleBadge({ role }: { role: AdminUserRecord['role'] }) { const { t } = useTranslation(); return <span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{t(userRoleKeys[role])}</span>; }
export function UserAdminList({ users, onChangeRole }: Props) { const { t } = useTranslation(); return <>
  <div className="hidden overflow-x-auto rounded-3xl border border-line bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900 md:block"><table className="w-full min-w-[680px] text-left"><caption className="sr-only">{t('admin.usersCaption')}</caption><thead className="border-b border-line text-sm text-muted dark:border-slate-700 dark:text-slate-300"><tr><th className="p-4 font-semibold">{t('admin.user')}</th><th className="p-4 font-semibold">{t('admin.username')}</th><th className="p-4 font-semibold">{t('admin.role')}</th><th className="p-4 text-right font-semibold">{t('admin.actions')}</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-line last:border-0 dark:border-slate-700"><td className="p-4"><div className="flex items-center gap-3"><Avatar name={user.name} /><span className="font-semibold break-words">{user.name}</span></div></td><td className="p-4 text-sm text-muted dark:text-slate-300">{user.username ? `@${user.username}` : t('admin.notInformed')}</td><td className="p-4"><RoleBadge role={user.role} /></td><td className="p-4 text-right"><button type="button" onClick={(event: { currentTarget: HTMLButtonElement }) => onChangeRole(user, event.currentTarget)} className="rounded-full border border-line px-4 py-2 text-sm font-semibold hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-teal-400 dark:hover:bg-slate-800">{t('admin.changeRole')}</button></td></tr>)}</tbody></table></div>
  <div className="grid gap-3 md:hidden">{users.map((user) => <article key={user.id} className="rounded-3xl border border-line bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex gap-3"><Avatar name={user.name} /><div className="min-w-0"><h2 className="font-semibold break-words">{user.name}</h2><p className="mt-1 text-sm text-muted dark:text-slate-300 break-all">{user.username ? `@${user.username}` : t('admin.usernameNotInformed')}</p><div className="mt-3"><RoleBadge role={user.role} /></div></div></div><button type="button" onClick={(event: { currentTarget: HTMLButtonElement }) => onChangeRole(user, event.currentTarget)} className="mt-4 w-full rounded-full border border-line px-4 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-teal-400">{t('admin.changeRole')}</button></article>)}</div>
</>; }
