import {useCallback,useEffect,useRef,useState} from 'react';
import {NotificationRepository} from '../repositories/notifications';
import type {NotificationPreferences} from '../types/notification';
const defaults:NotificationPreferences={contributions:true,comments:true,favorites:true,updatedAt:''};
export function useNotificationPreferences(userId?:string){
 const [preferences,setPreferences]=useState(defaults);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const generation=useRef(0);const active=useRef(userId);active.current=userId;
 const load=useCallback(async()=>{const account=userId;const token=++generation.current;if(!account||!NotificationRepository){setPreferences(defaults);setLoading(false);return;}setLoading(true);try{const result=await NotificationRepository.getPreferences();if(active.current!==account||token!==generation.current)return;if(result.ok)setPreferences(result.data);else setMessage(result.message);}catch{if(active.current===account&&token===generation.current)setMessage('Não foi possível carregar as preferências.');}finally{if(active.current===account&&token===generation.current)setLoading(false);}},[userId]);
 useEffect(()=>{setBusy(false);void load();return()=>{generation.current++;setBusy(false);};},[load]);
 const save=async(next:NotificationPreferences)=>{const account=userId;if(!account||!NotificationRepository)return false;const token=++generation.current;setBusy(true);setMessage('');try{const result=await NotificationRepository.updatePreferences(next);if(active.current!==account||token!==generation.current)return false;if(result.ok){setPreferences(next);window.dispatchEvent(new CustomEvent('notification-preferences-changed',{detail:next}));return true;}setMessage(result.message);return false;}catch{if(active.current===account&&token===generation.current)setMessage('Não foi possível salvar as preferências.');return false;}finally{if(token===generation.current)setBusy(false);}};
 const cleanup=async()=>{const account=userId;if(!account||!NotificationRepository)return null;const token=++generation.current;setBusy(true);setMessage('');try{const result=await NotificationRepository.cleanupRead();if(active.current!==account||token!==generation.current)return null;if(result.ok)return result.data;setMessage(result.message);return null;}catch{if(active.current===account&&token===generation.current)setMessage('Não foi possível limpar as notificações.');return null;}finally{if(token===generation.current)setBusy(false);}};
 return{preferences,loading,busy,message,save,cleanup};
}
