import { ExternalLink } from 'lucide-react';
import type { AdminContentKind, AdminContentRecord } from '../../../repositories/adminContent';

function date(value: string) { return value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informada'; }
function Link({ kind, id }: { kind: AdminContentKind; id: string }) { return <a href={`#/${kind === 'problem' ? 'problems' : 'solutions'}/${id}`} className="inline-flex items-center gap-2 rounded-full border border-line px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-teal-400"><ExternalLink size={15} aria-hidden="true" />Visualizar</a>; }
function Status({ record }: { record: AdminContentRecord }) { return <span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{record.status}{record.archived ? ' · arquivado' : ''}</span>; }
export function AdminContentList({ kind, records }: { kind: AdminContentKind; records: AdminContentRecord[] }) { const label = kind === 'problem' ? 'Problemas' : 'Soluções'; return <>
  <div className="hidden overflow-x-auto rounded-3xl border border-line bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900 md:block"><table className="w-full min-w-[900px] text-left"><caption className="sr-only">{label} disponíveis para consulta administrativa</caption><thead className="border-b border-line text-sm text-muted dark:border-slate-700 dark:text-slate-300"><tr><th className="p-4">Conteúdo</th><th className="p-4">Responsável</th><th className="p-4">Status</th><th className="p-4">Classificação</th><th className="p-4">Atualização</th><th className="p-4 text-right">Ações</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} className="border-b border-line align-top last:border-0 dark:border-slate-700"><td className="max-w-sm p-4"><strong className="block break-words">{record.title}</strong><p className="mt-1 line-clamp-2 text-sm text-muted dark:text-slate-300">{record.summary}</p>{kind === 'solution' && <p className="mt-2 text-xs text-muted dark:text-slate-300">{record.relatedProblems.length ? `Problema: ${record.relatedProblems.join(', ')}` : 'Sem problema relacionado'}</p>}{kind === 'problem' && record.relatedSolutionCount !== null && <p className="mt-2 text-xs text-muted dark:text-slate-300">{record.relatedSolutionCount} soluções relacionadas</p>}</td><td className="p-4 text-sm">{record.author}</td><td className="p-4"><Status record={record} /></td><td className="p-4 text-sm">{kind === 'solution' ? record.maturity ?? 'Não informada' : `${record.category} · ${record.region}`}</td><td className="p-4 text-sm">{date(record.updatedAt)}</td><td className="p-4 text-right"><Link kind={kind} id={record.id} /></td></tr>)}</tbody></table></div>
  <div className="grid gap-3 md:hidden">{records.map((record) => <article key={record.id} className="rounded-3xl border border-line bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="min-w-0 font-semibold break-words">{record.title}</h2><Status record={record} /></div><p className="mt-2 text-sm text-muted dark:text-slate-300">{record.summary}</p><dl className="mt-4 grid gap-2 text-sm"><div><dt className="font-semibold">Responsável</dt><dd>{record.author}</dd></div><div><dt className="font-semibold">{kind === 'solution' ? 'Maturidade' : 'Categoria e região'}</dt><dd>{kind === 'solution' ? record.maturity ?? 'Não informada' : `${record.category} · ${record.region}`}</dd></div><div><dt className="font-semibold">Atualização</dt><dd>{date(record.updatedAt)}</dd></div></dl><div className="mt-4"><Link kind={kind} id={record.id} /></div></article>)}</div>
</>; }
