import { ExternalLink } from 'lucide-react';
import type { AdminContentKind, AdminContentRecord, AdminContentStatus } from '../../../repositories/adminContent';
import { useTranslation } from '../../../i18n/I18nProvider';
import { formatDate, formatMessageCount } from '../../../i18n/format';
import { adminContentStatusKey } from '../../../i18n/presentation';

function Link({ kind, id }: { kind: AdminContentKind; id: string }) { const { t } = useTranslation(); return <a href={`#/${kind === 'problem' ? 'problems' : 'solutions'}/${id}`} className="inline-flex items-center gap-2 rounded-full border border-line px-3 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-teal-400"><ExternalLink size={15} aria-hidden="true" />{t('admin.view')}</a>; }
function Status({ kind, record }: { kind: AdminContentKind; record: AdminContentRecord }) { const { t } = useTranslation(); return <span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{t(adminContentStatusKey(kind, record.status as AdminContentStatus))}{record.archived ? ` · ${t('admin.archived')}` : ''}</span>; }
export function AdminContentList({ kind, records }: { kind: AdminContentKind; records: AdminContentRecord[] }) { const { locale, t } = useTranslation(); const label = t(kind === 'problem' ? 'nav.problems' : 'nav.solutions'); return <>
  <div className="hidden overflow-x-auto rounded-3xl border border-line bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900 md:block"><table className="w-full min-w-[900px] text-left"><caption className="sr-only">{t('admin.contentCaption', { kind: label })}</caption><thead className="border-b border-line text-sm text-muted dark:border-slate-700 dark:text-slate-300"><tr><th className="p-4">{t('admin.content')}</th><th className="p-4">{t('admin.owner')}</th><th className="p-4">{t('common.status')}</th><th className="p-4">{t('admin.classification')}</th><th className="p-4">{t('admin.updated')}</th><th className="p-4 text-right">{t('admin.actions')}</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} className="border-b border-line align-top last:border-0 dark:border-slate-700"><td className="max-w-sm p-4"><strong className="block break-words">{record.title}</strong><p className="mt-1 line-clamp-2 text-sm text-muted dark:text-slate-300">{record.summary}</p>{kind === 'solution' && <p className="mt-2 text-xs text-muted dark:text-slate-300">{record.relatedProblems.length ? t('admin.relatedProblem', { titles: record.relatedProblems.join(', ') }) : t('admin.noRelatedProblem')}</p>}{kind === 'problem' && record.relatedSolutionCount !== null && <p className="mt-2 text-xs text-muted dark:text-slate-300">{formatMessageCount(record.relatedSolutionCount, locale, t, 'admin.relatedSolutions.one', 'admin.relatedSolutions.other')}</p>}</td><td className="p-4 text-sm">{record.author}</td><td className="p-4"><Status kind={kind} record={record} /></td><td className="p-4 text-sm">{kind === 'solution' ? record.maturity ?? t('admin.dateMissing') : `${record.category} · ${record.region}`}</td><td className="p-4 text-sm">{formatDate(record.updatedAt, locale, t('admin.dateMissing'))}</td><td className="p-4 text-right"><Link kind={kind} id={record.id} /></td></tr>)}</tbody></table></div>
  <div className="grid gap-3 md:hidden">{records.map((record) => <article key={record.id} className="rounded-3xl border border-line bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="min-w-0 font-semibold break-words">{record.title}</h2><Status kind={kind} record={record} /></div><p className="mt-2 text-sm text-muted dark:text-slate-300">{record.summary}</p><dl className="mt-4 grid gap-2 text-sm"><div><dt className="font-semibold">{t('admin.owner')}</dt><dd>{record.author}</dd></div><div><dt className="font-semibold">{t(kind === 'solution' ? 'admin.maturity' : 'admin.categoryRegion')}</dt><dd>{kind === 'solution' ? record.maturity ?? t('admin.dateMissing') : `${record.category} · ${record.region}`}</dd></div><div><dt className="font-semibold">{t('admin.updated')}</dt><dd>{formatDate(record.updatedAt, locale, t('admin.dateMissing'))}</dd></div></dl><div className="mt-4"><Link kind={kind} id={record.id} /></div></article>)}</div>
</>; }
