import { ArrowLeft, Search } from 'lucide-react';
import { useEffect, useState, type ChangeEvent } from 'react';
import { AdminContentList } from '../components/admin/content/AdminContentList';
import { resetAdminContentPage } from '../components/admin/content/adminContentPageState';
import { ADMIN_CONTENT_PAGE_SIZE, adminContentStatuses, type AdminContentKind, type AdminContentStatus } from '../repositories/adminContent';
import { useAdminContent } from '../hooks/useAdminContent';
import { useAuth } from '../hooks/useAuth';
import { usePermissions } from '../hooks/usePermissions';

export function AdminContentPage({ kind, onBack }: { kind: AdminContentKind; onBack: () => void }) {
  const { user } = useAuth(); const permissions = usePermissions(user); const [page, setPage] = useState(0); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState<AdminContentStatus | 'all'>('all');
  useEffect(() => { const timer = window.setTimeout(() => setSearch(input), 250); return () => window.clearTimeout(timer); }, [input]);
  useEffect(() => { setPage(resetAdminContentPage()); }, [kind, search, status]);
  const content = useAdminContent(kind, permissions.canAccessAdmin, { page, search, status });
  const isProblem = kind === 'problem'; const title = isProblem ? 'Gestão de problemas' : 'Gestão de soluções'; const noun = isProblem ? 'problemas' : 'soluções';
  return <section className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-teal-700 dark:text-teal-300">Administração</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{title}</h1><p className="mt-3 max-w-2xl text-muted dark:text-slate-300">Consulte o catálogo disponível com campos públicos seguros. Ações de status e exclusão não são oferecidas sem RPC administrativa auditada.</p></div><button type="button" onClick={onBack} className="inline-flex items-center gap-2 rounded-full border border-line px-4 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-teal-400"><ArrowLeft size={16} aria-hidden="true" />Voltar ao painel</button></header>
    <div className="grid gap-3 rounded-3xl border border-line bg-white p-4 dark:border-slate-700 dark:bg-slate-900 md:grid-cols-[1fr_240px]"><label className="flex items-center rounded-2xl border border-line px-3 focus-within:ring-2 focus-within:ring-teal-400 dark:bg-slate-950"><Search size={18} aria-hidden="true" className="text-muted" /><span className="sr-only">Buscar {noun}</span><input value={input} onChange={(event: ChangeEvent<HTMLInputElement>) => setInput(event.target.value)} placeholder="Buscar por título, resumo, responsável, categoria ou região" className="w-full bg-transparent p-3 text-sm outline-none" /></label><label><span className="sr-only">Filtrar por status</span><select value={status} onChange={(event: ChangeEvent<HTMLSelectElement>) => setStatus(event.target.value as AdminContentStatus | 'all')} className="w-full rounded-2xl border border-line bg-white p-3 text-sm focus:outline-none focus:ring-2 focus:ring-teal-400 dark:bg-slate-950"><option value="all">Todos os status</option>{adminContentStatuses(kind).map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div>
    <p aria-live="polite" className="text-sm text-muted dark:text-slate-300">{content.loading ? `Carregando ${noun}…` : `${content.total} ${content.total === 1 ? noun.slice(0, -1) : noun} encontrados${content.records.length ? `; ${content.records.length} visíveis nesta página.` : '.'}`}</p><p aria-live="assertive" className="text-sm font-semibold text-rose-700 dark:text-rose-300">{content.error}</p>
    {content.loading ? <div role="status" className="rounded-3xl border border-line bg-white p-8 text-center text-muted dark:border-slate-700 dark:bg-slate-900">Carregando catálogo administrativo…</div> : content.error ? <button type="button" onClick={content.retry} className="rounded-full border border-line px-4 py-2 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-teal-400">Tentar novamente</button> : !content.records.length ? <div className="rounded-3xl border border-dashed border-line bg-white p-8 text-center dark:border-slate-700 dark:bg-slate-900"><h2 className="font-semibold">Nenhum resultado encontrado</h2><p className="mt-2 text-sm text-muted dark:text-slate-300">Ajuste a busca ou o filtro para consultar outros registros.</p></div> : <AdminContentList kind={kind} records={content.records} />}
    {!content.error && !content.loading && <nav aria-label="Paginação" className="flex items-center justify-between gap-3"><button type="button" disabled={page === 0} onClick={() => setPage((value) => value - 1)} className="rounded-full border border-line px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50">Anterior</button><span className="text-sm text-muted dark:text-slate-300">Página {page + 1}</span><button type="button" disabled={(page + 1) * ADMIN_CONTENT_PAGE_SIZE >= content.total} onClick={() => setPage((value) => value + 1)} className="rounded-full border border-line px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50">Próxima</button></nav>}
  </section>;
}
