import { useMemo, useState, type ChangeEvent } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useContributions } from '../hooks/useContributions';
import { ContributionDiff } from '../components/contributions/ContributionDiff';
import { contributionStatusLabel, type ContributionStatus } from '../types/contribution';

export function ContributionsList({ onNavigate }: { onNavigate: (page: string) => void }) { const { user } = useAuth(); const { contributions, loading, error } = useContributions(user); const [filter, setFilter] = useState<ContributionStatus | 'all'>('all'); const mine = useMemo(() => contributions.filter((x) => x.userId === user?.id && (filter === 'all' || x.status === filter)), [contributions, filter, user]); return <section className="space-y-6"><div><h1 className="text-4xl font-semibold">Minhas contribuições</h1><p className="mt-2 text-muted">Acompanhe propostas pendentes, aprovadas e rejeitadas.</p></div><select className="rounded-2xl border p-3" value={filter} onChange={(e: ChangeEvent<HTMLSelectElement>) => setFilter(e.target.value as ContributionStatus | 'all')}><option value="all">Todas</option><option value="pending">Pendentes</option><option value="approved">Aprovadas</option><option value="rejected">Rejeitadas</option></select>{error && <p role="alert">{error}</p>}{loading ? <p>Carregando...</p> : mine.length ? mine.map((x) => <button key={x.id} onClick={() => onNavigate(`contribution:${x.id}`)} className="block w-full rounded-3xl border bg-white p-5 text-left"><strong>{x.targetTitle}</strong><p className="text-sm text-muted">{x.targetType === 'problem' ? 'Problema' : 'Solução'} · {new Date(x.createdAt).toLocaleDateString('pt-BR')} · {contributionStatusLabel[x.status]}</p></button>) : <p className="rounded-3xl border border-dashed p-8 text-center">Nenhuma contribuição encontrada.</p>}</section>; }

export function ContributionDetails({ id }: { id: string }) { const { user } = useAuth(); const { contributions, loading } = useContributions(user); const item = contributions.find((x) => x.id === id); if (loading) return <p>Carregando...</p>; if (!item) return <p>Contribuição não encontrada.</p>; return <section className="space-y-5"><div className="rounded-3xl border bg-white p-6"><p className="text-teal-700">{contributionStatusLabel[item.status]}</p><h1 className="text-3xl font-semibold">{item.payload.title || item.targetTitle}</h1><p className="mt-2">Alvo: {item.targetTitle} · {new Date(item.createdAt).toLocaleString('pt-BR')}</p><h2 className="mt-5 font-semibold">Resumo</h2><p>{item.payload.summary}</p><h2 className="mt-4 font-semibold">Descrição</h2><p>{item.payload.description}</p>{item.rejectionReason && <p className="mt-4 rounded-2xl bg-rose-50 p-4">Motivo: {item.rejectionReason}</p>}</div><ContributionDiff changes={item.payload.changes.map((x, index) => ({ ...x, id: `${index}` }))} /></section>; }
