import { useMemo, useState, type ChangeEvent } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useContributions } from '../hooks/useContributions';
import { ContributionDiff } from '../components/contributions/ContributionDiff';
import { canEditContribution, canWithdrawContribution } from '../lib/authorship';
import { contributionStatusLabel, type ContributionStatus } from '../types/contribution';

export function ContributionsList({ onNavigate }: { onNavigate: (page: string) => void }) {
  const { user } = useAuth(); const hook = useContributions(user); const [filter, setFilter] = useState<ContributionStatus | 'all'>('all'); const [feedback, setFeedback] = useState('');
  const mine = useMemo(() => hook.contributions.filter((x) => x.userId === user?.id && (filter === 'all' || x.status === filter)), [hook.contributions, filter, user]);
  const withdraw = async (id: string) => { if (!window.confirm('Retirar esta contribuição?')) return; const result = await hook.withdrawContribution(id); setFeedback(result.ok ? 'Contribuição retirada.' : result.message); };
  return <section className="space-y-6"><div><h1 className="text-4xl font-semibold">Minhas contribuições</h1><p className="mt-2 text-muted">Acompanhe e responda às solicitações de ajuste.</p></div><label className="grid max-w-xs gap-1">Status<select className="rounded-2xl border p-3" value={filter} onChange={(e: ChangeEvent<HTMLSelectElement>) => setFilter(e.target.value as ContributionStatus | 'all')}><option value="all">Todas</option>{Object.entries(contributionStatusLabel).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><p role="status" aria-live="polite">{feedback}</p>{hook.error && <p role="alert">{hook.error}</p>}{hook.loading ? <p>Carregando...</p> : mine.length ? mine.map((x) => <article key={x.id} className="rounded-3xl border bg-white p-5"><button onClick={() => onNavigate(`contribution:${x.id}`)} className="w-full text-left"><strong>{x.targetTitle}</strong><p className="text-sm text-muted">{x.targetType === 'problem' ? 'Problema' : 'Solução'} · {new Date(x.createdAt).toLocaleDateString('pt-BR')} · {contributionStatusLabel[x.status]}</p></button><div className="mt-3 flex gap-2">{canEditContribution(user?.id, x) && <button onClick={() => onNavigate(`contribution:${x.id}`)} className="rounded-full border px-3 py-2 text-sm">{x.status === 'changes_requested' ? 'Responder ajustes' : 'Editar'}</button>}{canWithdrawContribution(user?.id, x) && <button onClick={() => void withdraw(x.id)} className="rounded-full border border-rose-200 px-3 py-2 text-sm text-rose-700">Retirar</button>}<button onClick={() => onNavigate(`${x.targetType === 'problem' ? 'problema' : 'solucao'}:${x.targetId}`)} className="rounded-full border px-3 py-2 text-sm">Abrir conteúdo</button></div></article>) : <p className="rounded-3xl border border-dashed p-8 text-center">Nenhuma contribuição encontrada.</p>}</section>;
}
export function ContributionDetails({ id }: { id: string }) { const { user } = useAuth(); const { contributions, loading } = useContributions(user); const item = contributions.find((x) => x.id === id); if (loading) return <p>Carregando...</p>; if (!item) return <p>Contribuição não encontrada.</p>; return <section className="space-y-5"><div className="rounded-3xl border bg-white p-6"><p className="text-teal-700">{contributionStatusLabel[item.status]}</p><h1 className="text-3xl font-semibold">{item.payload.title || item.targetTitle}</h1><p className="mt-2">Alvo: {item.targetTitle} · {new Date(item.createdAt).toLocaleString('pt-BR')}</p><h2 className="mt-5 font-semibold">Justificativa</h2><p>{item.payload.summary}</p><h2 className="mt-4 font-semibold">Descrição</h2><p>{item.payload.description}</p>{item.rejectionReason && <p className="mt-4 rounded-2xl bg-rose-50 p-4">Motivo: {item.rejectionReason}</p>}</div><ContributionDiff changes={item.payload.changes.map((x, index) => ({ ...x, id: `${index}` }))} /></section>; }
