import { useMemo, useState, type ChangeEvent } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useContributions } from '../hooks/useContributions';
import { ContributionDiff } from '../components/contributions/ContributionDiff';
import { canEditContribution, canWithdrawContribution } from '../lib/authorship';
import type { ContributionStatus } from '../types/contribution';
import { useTranslation } from '../i18n/I18nProvider';
import { formatDate, formatDateTime } from '../i18n/format';
import { contributionStatusKeys } from '../i18n/presentation';

export function ContributionsList({ onNavigate }: { onNavigate: (page: string) => void }) {
  const { locale, t } = useTranslation();
  const { user } = useAuth(); const hook = useContributions(user); const [filter, setFilter] = useState<ContributionStatus | 'all'>('all'); const [feedback, setFeedback] = useState('');
  const mine = useMemo(() => hook.contributions.filter((x) => x.userId === user?.id && (filter === 'all' || x.status === filter)), [hook.contributions, filter, user]);
  const withdraw = async (id: string) => { if (!window.confirm(t('contributions.withdrawConfirm'))) return; const result = await hook.withdrawContribution(id); setFeedback(result.ok ? t('contributions.withdrawn') : result.message); };
  return <section className="space-y-6"><div><h1 className="text-4xl font-semibold">{t('contributions.title')}</h1><p className="mt-2 text-muted">{t('contributions.description')}</p></div><label className="grid max-w-xs gap-1">{t('common.statusLabel')}<select className="rounded-2xl border p-3" value={filter} onChange={(e: ChangeEvent<HTMLSelectElement>) => setFilter(e.target.value as ContributionStatus | 'all')}><option value="all">{t('common.allFemale')}</option>{(Object.keys(contributionStatusKeys) as ContributionStatus[]).map((value) => <option key={value} value={value}>{t(contributionStatusKeys[value])}</option>)}</select></label><p role="status" aria-live="polite">{feedback}</p>{hook.error && <p role="alert">{hook.error}</p>}{hook.loading ? <p>{t('common.loadingDots')}</p> : mine.length ? mine.map((x) => <article key={x.id} className="rounded-3xl border bg-white p-5"><button onClick={() => onNavigate(`contribution:${x.id}`)} className="w-full text-left"><strong>{x.targetTitle}</strong><p className="text-sm text-muted">{t(x.targetType === 'problem' ? 'domain.problem' : 'domain.solution')} · {formatDate(x.createdAt, locale)} · {t(contributionStatusKeys[x.status])}</p></button><div className="mt-3 flex gap-2">{canEditContribution(user?.id, x) && <button onClick={() => onNavigate(`contribution:${x.id}`)} className="rounded-full border px-3 py-2 text-sm">{x.status === 'changes_requested' ? t('contributions.respond') : t('common.edit')}</button>}{canWithdrawContribution(user?.id, x) && <button onClick={() => void withdraw(x.id)} className="rounded-full border border-rose-200 px-3 py-2 text-sm text-rose-700">{t('contributions.withdraw')}</button>}<button onClick={() => onNavigate(`${x.targetType === 'problem' ? 'problema' : 'solucao'}:${x.targetId}`)} className="rounded-full border px-3 py-2 text-sm">{t('contributions.openContent')}</button></div></article>) : <p className="rounded-3xl border border-dashed p-8 text-center">{t('contributions.empty')}</p>}</section>;
}
export function ContributionDetails({ id }: { id: string }) { const { locale, t } = useTranslation(); const { user } = useAuth(); const { contributions, loading } = useContributions(user); const item = contributions.find((x) => x.id === id); if (loading) return <p>{t('common.loadingDots')}</p>; if (!item) return <p>{t('contributions.notFound')}</p>; return <section className="space-y-5"><div className="rounded-3xl border bg-white p-6"><p className="text-teal-700">{t(contributionStatusKeys[item.status])}</p><h1 className="text-3xl font-semibold">{item.payload.title || item.targetTitle}</h1><p className="mt-2">{t('contributions.target', { title: item.targetTitle })} · {formatDateTime(item.createdAt, locale)}</p><h2 className="mt-5 font-semibold">{t('contributions.justification')}</h2><p>{item.payload.summary}</p><h2 className="mt-4 font-semibold">{t('common.descriptionLabel')}</h2><p>{item.payload.description}</p>{item.rejectionReason && <p className="mt-4 rounded-2xl bg-rose-50 p-4">{t('contributions.reason', { reason: item.rejectionReason })}</p>}</div><ContributionDiff changes={item.payload.changes.map((x, index) => ({ ...x, id: `${index}` }))} /></section>; }
