let taxonomyIdSequence=0;
import { useState, type ChangeEvent } from 'react';
import { useTaxonomy } from '../../hooks/useTaxonomy';
import type { TaxonomyKind, TaxonomyScope } from '../../types/taxonomy';

export function TaxonomySelect({kind,scope,value,onChange,label,required=false}:{kind:TaxonomyKind;scope:TaxonomyScope;value:string;onChange:(value:string)=>void;label:string;required?:boolean}){
 const [id]=useState(()=>`taxonomy-${++taxonomyIdSequence}`),[query,setQuery]=useState('');const {terms,loading,error,retry}=useTaxonomy(kind,scope,query);
 return <fieldset className="grid gap-2 text-sm font-medium"><legend>{label}{required?' *':''}</legend><input id={`${id}-search`} aria-label={`Pesquisar ${label.toLowerCase()}`} value={query} onChange={(e:ChangeEvent<HTMLInputElement>)=>setQuery(e.target.value)} className="rounded-2xl border border-line p-3" placeholder="Pesquisar termos aprovados"/><select id={id} aria-label={label} required={required} value={value} onChange={(e:ChangeEvent<HTMLSelectElement>)=>onChange(e.target.value)} className="rounded-2xl border border-line p-3" disabled={loading}><option value="">Selecione</option>{terms.map(term=><option key={term.id} value={term.name}>{term.name}</option>)}</select>{loading&&<span role="status">Carregando opções…</span>}{!loading&&!error&&!terms.length&&<span>Nenhum termo aprovado.</span>}{error&&<span role="alert" className="text-red-700">{error} <button type="button" onClick={()=>void retry()} className="underline">Tentar novamente</button></span>}</fieldset>;
}

export function TaxonomyMultiSelect({scope,value,onChange,label='Tags'}:{scope:TaxonomyScope;value:string[];onChange:(value:string[])=>void;label?:string}){
 const [id]=useState(()=>`taxonomy-${++taxonomyIdSequence}`),[query,setQuery]=useState('');const {terms,loading,error,retry}=useTaxonomy('tag',scope,query);return <fieldset className="grid gap-2"><legend className="text-sm font-medium">{label}</legend><input id={id} value={query} onChange={(e:ChangeEvent<HTMLInputElement>)=>setQuery(e.target.value)} aria-label="Pesquisar tags aprovadas" placeholder="Pesquisar tags; para uma nova, use Sugerir termo" className="rounded-2xl border p-3"/>{loading?<span role="status">Carregando tags…</span>:error?<span role="alert">{error} <button type="button" onClick={()=>void retry()}>Tentar novamente</button></span>:terms.length?<div className="flex flex-wrap gap-2">{terms.map(term=><label key={term.id} className="rounded-full border px-3 py-2"><input type="checkbox" checked={value.includes(term.name)} onChange={()=>onChange(value.includes(term.name)?value.filter(x=>x!==term.name):[...value,term.name].slice(0,20))}/> {term.name}</label>)}</div>:<span>Nenhuma tag aprovada.</span>}</fieldset>;
}
