let taxonomyProposalIdSequence = 0;
import { useState, type ChangeEvent, type FormEvent } from 'react';
import { useTaxonomyProposals } from '../../hooks/useTaxonomy';
import type { TaxonomyKind, TaxonomyScope, TaxonomyProposalStatus } from '../../types/taxonomy';
import { useTranslation } from '../../i18n/I18nProvider';
import type { TranslationKey } from '../../i18n/resources';
const statusKeys: Record<TaxonomyProposalStatus, TranslationKey> = { pending:'taxonomy.status.pending', approved:'taxonomy.status.approved', rejected:'taxonomy.status.rejected' };
export function TaxonomyProposalForm({ kind, scope }: { kind: TaxonomyKind; scope: TaxonomyScope }) {
  const { t } = useTranslation(); const [id] = useState(() => `taxonomy-proposal-${++taxonomyProposalIdSequence}`), [name, setName] = useState(''), [reason, setReason] = useState(''); const hook = useTaxonomyProposals('mine');
  return <section className="space-y-4"><form className="grid gap-3 rounded-2xl border p-4" onSubmit={async (event: FormEvent) => { event.preventDefault(); const result = await hook.propose(name, kind, scope, reason); if (result.ok) { setName(''); setReason(''); } }}><h3 className="font-semibold">{t('taxonomy.suggest')}</h3><label htmlFor={`${id}-name`}>{t('common.name')}</label><input id={`${id}-name`} required maxLength={80} value={name} onChange={(event: ChangeEvent<HTMLInputElement>) => setName(event.target.value)} className="rounded-xl border p-3" /><label htmlFor={`${id}-reason`}>{t('contributions.justification')}</label><textarea id={`${id}-reason`} required minLength={10} maxLength={1000} value={reason} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => setReason(event.target.value)} className="rounded-xl border p-3" /><button disabled={hook.submitting} className="rounded-full bg-teal-700 px-4 py-2 text-white disabled:opacity-50">{hook.submitting ? t('taxonomy.sending') : t('taxonomy.submit')}</button><p aria-live="polite">{hook.message || hook.error}</p></form><section><h3 className="font-semibold">{t('taxonomy.mine')}</h3>{hook.loading ? <p>{t('common.loading')}</p> : hook.error ? <button onClick={() => void hook.retry()}>{t('common.retry')}</button> : hook.items.length ? hook.items.map((item) => <p key={item.id}>{item.proposedName} · {t(statusKeys[item.status])}</p>) : <p>{t('taxonomy.emptyMine')}</p>}</section></section>;
}
