import assert from 'node:assert/strict';
import test from 'node:test';
import { COMMENT_REACTION_TYPES, parseCommentReactionSummaries } from '../src/repositories/reactions/commentReactionCore.ts';
import { ReactionOperationController } from '../src/hooks/reactionOperationController.ts';
const deferred=<T>()=>{let resolve!:(value:T)=>void;let reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}};

test('summary parser maps four types and explicit anonymous false',()=>{const rows=COMMENT_REACTION_TYPES.map((reaction_type,index)=>({comment_id:'comment',reaction_type,reaction_count:index,selected_by_user:false}));const result=parseCommentReactionSummaries(rows);assert.equal(result.ok,true);if(result.ok)for(const type of COMMENT_REACTION_TYPES)assert.equal(result.data.comment[type].selected,false)});
test('summary parser rejects nullable selection, malformed response, and identities',()=>{assert.equal(parseCommentReactionSummaries([{comment_id:'c',reaction_type:'like',reaction_count:1,selected_by_user:null}]).ok,false);assert.equal(parseCommentReactionSummaries({}).ok,false);assert.equal(parseCommentReactionSummaries([{comment_id:'c',reaction_type:'like',reaction_count:1,selected_by_user:false,user_id:'other'}]).ok,false)});

test('first and second sequential clicks both run',async()=>{const controller=new ReactionOperationController();let calls=0;assert.equal((await controller.run('c:like',async()=>++calls)).status,'success');assert.equal((await controller.run('c:like',async()=>++calls)).status,'success');assert.equal(calls,2)});
test('double click before render and concurrent same-key call invoke one RPC',async()=>{const controller=new ReactionOperationController();const gate=deferred<number>();let calls=0;const first=controller.run('c:like',()=>{calls++;return gate.promise});const second=controller.run('c:like',async()=>{calls++;return 2});assert.equal((await second).status,'duplicate');assert.equal(calls,1);gate.resolve(1);assert.equal((await first).status,'success');assert.equal(controller.isPending('c:like'),false)});
test('different keys run independently',async()=>{const controller=new ReactionOperationController();const a=deferred<number>();const b=deferred<number>();const one=controller.run('c:like',()=>a.promise);const two=controller.run('c:support',()=>b.promise);assert.deepEqual(controller.pendingKeys(),new Set(['c:like','c:support']));b.resolve(2);a.resolve(1);assert.equal((await one).status,'success');assert.equal((await two).status,'success')});
test('success can commit optimistic state',async()=>{const controller=new ReactionOperationController();let selected=false;selected=true;const outcome=await controller.run('c:like',async()=>({active:true,count:1}));if(outcome.status==='success')selected=outcome.value.active;assert.equal(selected,true)});
test('repository failure rolls optimistic state back',async()=>{const controller=new ReactionOperationController();let selected=true;const previous=false;const outcome=await controller.run('c:like',async()=>({ok:false}));if(outcome.status==='success'&&!outcome.value.ok)selected=previous;assert.equal(selected,false)});
test('thrown RPC is sanitized and finally releases key',async()=>{const controller=new ReactionOperationController();const outcome=await controller.run('c:like',async()=>{throw new Error('private SQL')});assert.equal(outcome.status,'error');assert.equal(controller.isPending('c:like'),false)});
test('logout discards response and clears pending operation',async()=>{const controller=new ReactionOperationController();const gate=deferred<number>();const old=controller.run('c:like',()=>gate.promise);controller.reset();assert.equal(controller.isPending('c:like'),false);gate.resolve(1);assert.equal((await old).status,'discarded')});
test('account change lets new same-key work survive old finally',async()=>{const controller=new ReactionOperationController();const oldGate=deferred<number>();const old=controller.run('c:like',()=>oldGate.promise);controller.reset();const newGate=deferred<number>();const current=controller.run('c:like',()=>newGate.promise);oldGate.resolve(1);assert.equal((await old).status,'discarded');assert.equal(controller.isPending('c:like'),true);newGate.resolve(2);assert.equal((await current).status,'success');assert.equal(controller.isPending('c:like'),false)});
test('finally cleans a failed current operation',async()=>{const controller=new ReactionOperationController();await controller.run('c:like',async()=>Promise.reject(new Error('fail')));assert.deepEqual(controller.pendingKeys(),new Set())});
