import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { globSync } from 'node:fs';
const migration = readFileSync('supabase/migrations/20260722290000_sprint29_authenticated_actions.sql', 'utf8');
assert.match(migration, /revoke insert, update, delete[\s\S]+from anon/i);
for (const catalogTerm of ['pg_proc', 'pg_namespace', 'oid::regprocedure']) assert.match(migration, new RegExp(catalogTerm, 'i'));
assert.match(migration, /execute format\('revoke all on function %s from public, anon'/i);
assert.match(migration, /execute format\('grant execute on function %s to authenticated'/i);
assert.match(migration, /revoke all on function %s from authenticated/i);
assert.match(migration, /storage\.objects[\s\S]+for insert to authenticated/i);
assert.doesNotMatch(migration, /service_role/i);
const all = globSync('supabase/migrations/*.sql').map((p) => readFileSync(p, 'utf8')).join('\n');
for (const rpc of ['report_comment', 'mark_comment_best_answer', 'moderate_comment_visibility', 'review_contribution', 'publish_problem_update']) assert.match(all, new RegExp(`function public\\.${rpc}[\\s\\S]{0,2500}auth\\.uid\\(\\)`, 'i'));
console.log('Sprint 29 static authorization audit passed.');

const route = readFileSync('src/components/auth/AuthenticatedRoute.tsx', 'utf8');
const app = readFileSync('src/App.tsx', 'utf8');
assert.match(route, /useEffect\([\s\S]*saveAuthReturnTo\(\)[\s\S]*onLoginRequired\(\)/);
assert.doesNotMatch(route.slice(0, route.indexOf('useEffect')), /saveAuthReturnTo|onLoginRequired\(/);
assert.doesNotMatch(app, /privatePage|saveAuthReturnTo\(\);[\s\S]*setPage\('login'\)/);
assert.match(app, /const redirectToLogin = useCallback/);
console.log('Sprint 29 route authority audit passed.');

const storage = new Map<string, string>();
Object.assign(globalThis, { window: { location: { hash: '#/problems/new' }, sessionStorage: { getItem: (key: string) => storage.get(key) ?? null, setItem: (key: string, value: string) => storage.set(key, value), removeItem: (key: string) => storage.delete(key) } } });
const returns = await import('../src/components/auth/authReturnTo.ts');
returns.saveAuthReturnTo();
assert.equal(returns.consumeAuthReturnTo(), '#/problems/new', 'the protected route is preserved');
window.location.hash = '#/favorites'; returns.saveAuthReturnTo();
window.location.hash = '#/profile'; returns.saveAuthReturnTo();
assert.equal(returns.consumeAuthReturnTo(), '#/favorites', 'a valid return is saved once per access attempt');
window.location.hash = '#/problems/new'; returns.saveAuthReturnTo();
window.location.hash = '#/login'; returns.saveAuthReturnTo();
assert.equal(returns.consumeAuthReturnTo(), '#/problems/new', 'login never overwrites the protected return');
console.log('Sprint 29 return preservation audit passed.');
