import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { TaxonomyRepositoryCore } from '../src/repositories/taxonomy/TaxonomyRepositoryCore.ts';
const migration=readFileSync('supabase/migrations/20260726130000_sprint35_global_taxonomy.sql','utf8');
const workflow=readFileSync('.github/workflows/deploy.yml','utf8');
const assertions=readFileSync('scripts/fixtures/sprint35_taxonomy_assertions.sql','utf8');
test('migration is additive and preserves compatibility columns and RPCs',()=>{assert.doesNotMatch(migration,/drop\s+(?:column|function|table)|alter\s+column\s+(?:category|tags)/i);for(const name of ['search_problems','search_solutions','search_nearby_problems','search_nearby_solutions','get_related_problems','get_recommended_solutions','get_related_problems_for_solution'])assert.doesNotMatch(migration,new RegExp(`create(?: or replace)? function public\\.${name}`,'i'))});
test('canonical vocabulary, proposals and append-only audit are protected',()=>{for(const table of ['taxonomy_terms','taxonomy_aliases','taxonomy_proposals','taxonomy_audit']){assert.match(migration,new RegExp(`create table public\\.${table}`));assert.match(migration,new RegExp(`alter table public\\.${table} enable row level security`))}assert.match(migration,/before insert or update of category,tags on public\.problems/);assert.match(migration,/before insert or update of category,tags on public\.solutions/);assert.doesNotMatch(migration,/delete from public\.taxonomy_audit|update public\.taxonomy_audit/i)});
test('moderation uses existing roles, locking, idempotency and fixed search path',()=>{assert.match(migration,/role::text in \('curator','admin'\)/);assert.match(migration,/for update/);assert.match(migration,/if p\.status<>'pending'/);assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/review_taxonomy_proposal[\s\S]*security definer set search_path=public,pg_catalog/);assert.doesNotMatch(migration,/service_role|execute format\(/i)});
test('PostgreSQL 15 CI applies real migration then assertions',()=>{assert.match(workflow,/image: postgres:15/);const m='-f supabase/migrations/20260726130000_sprint35_global_taxonomy.sql',a='-f scripts/fixtures/sprint35_taxonomy_assertions.sql';assert.ok(workflow.includes(m));assert.ok(workflow.includes(a));assert.ok(workflow.indexOf(m)<workflow.indexOf(a));assert.doesNotMatch(workflow,/continue-on-error|migration repair/i);assert.match(assertions,/search_problems/);assert.match(assertions,/get_recommended_solutions/)});
test('frontend follows repository and hook boundary',()=>{const component=readFileSync('src/components/taxonomy/TaxonomySelect.tsx','utf8');const repository=readFileSync('src/repositories/taxonomy/TaxonomyRepository.ts','utf8')+readFileSync('src/repositories/taxonomy/TaxonomyRepositoryCore.ts','utf8');assert.doesNotMatch(component,/supabaseClient|integrations\/supabase/);assert.match(component,/useTaxonomy/);assert.match(repository,/list_taxonomy_terms/)});
test('taxonomy repository maps approved terms and sends typed proposal parameters',async()=>{const calls:Array<{name:string;params:Record<string,unknown>}>=[];const client={rpc:async(name:string,params:Record<string,unknown>)=>{calls.push({name,params});return name==='list_taxonomy_terms'?{data:[{id:'term-1',kind:'category',scope:'both',name:'Cultura',slug:'cultura',total_count:1}],error:null}:{data:'proposal-1',error:null}}};const repository=new TaxonomyRepositoryCore(client);const listed=await repository.list('category','problem','cult');assert.equal(listed.ok,true);if(listed.ok){assert.equal(listed.data.items[0].name,'Cultura');assert.equal(listed.data.total,1)}const proposed=await repository.propose('Nova tag','tag','problem','Justificativa válida');assert.deepEqual(proposed,{ok:true,id:'proposal-1'});assert.deepEqual(calls[1],{name:'submit_taxonomy_proposal',params:{p_name:'Nova tag',p_kind:'tag',p_scope:'problem',p_justification:'Justificativa válida'}})});
test('dynamic category parsing and curator permissions are explicit',()=>{const problemRepository=readFileSync('src/repositories/problems/ProblemRepository.ts','utf8'),solutionRepository=readFileSync('src/repositories/solutions/SolutionRepository.ts','utf8'),permissions=readFileSync('src/hooks/usePermissions.ts','utf8');assert.match(problemRepository,/safeCategory\(row\.category\)/);assert.match(solutionRepository,/safeCategory\(row\.category\)/);assert.doesNotMatch(problemRepository,/categories.*Outros/);assert.match(permissions,/canReviewTaxonomy: isAdmin \|\| hasRole\(user, \['curator'\]\)/)});

test('taxonomy moderation has a dedicated permission-gated route',()=>{const app=readFileSync('src/App.tsx','utf8'),layout=readFileSync('src/components/Layout.tsx','utf8');assert.match(app,/admin-taxonomy.*\/admin\/taxonomy/);assert.match(app,/page === 'admin-taxonomy'[\s\S]*permissions\.canReviewTaxonomy/);assert.match(layout,/permissions\.canReviewTaxonomy[\s\S]*admin-taxonomy/);assert.doesNotMatch(app,/admin-contributions'.*canReviewTaxonomy/) });

test('backfill has deterministic display capitalization policy',()=>{assert.match(migration,/max\(name\) filter\(where curated\)/);assert.match(migration,/case when kind='tag' then public\.normalize_taxonomy_name\(name\)/);assert.match(assertions,/tags[^\n]*<>array\['drenagem'\]/);assert.match(assertions,/lower\(name\)=lower\('DRENAGEM'\)/)});
test('proposals are RPC-only for authenticated users',()=>{assert.doesNotMatch(migration,/policy proposals_own_insert|grant select,insert on public\.taxonomy_proposals/);assert.match(migration,/grant select on public\.taxonomy_proposals to authenticated/);assert.match(assertions,/direct proposal insert accepted/);assert.match(assertions,/submit_taxonomy_proposal\('Tag do usuário A'/)});
test('moderation queue exposes essential review context',()=>{const queue=readFileSync('src/components/admin/TaxonomyProposalQueue.tsx','utf8');for(const field of ['item.kind','item.scope','item.authorId','item.createdAt','item.justification'])assert.ok(queue.includes(field),`queue missing ${field}`);for(const label of ['Tipo:','Escopo:','Autor:','Data da proposta:','Justificativa:'])assert.ok(queue.includes(label),`queue missing ${label}`)});
test('taxonomy selections remain visible while search results change',()=>{const component=readFileSync('src/components/taxonomy/TaxonomySelect.tsx','utf8');assert.match(component,/value&&!terms\.some[\s\S]*\{value\} \(selecionado\)/);assert.match(component,/aria-label="Tags selecionadas"[\s\S]*value\.map/)});
test('isolated auth fixture grants only the access needed by SET ROLE scenarios',()=>{const fixture=readFileSync('scripts/fixtures/sprint32_search_schema.sql','utf8');assert.match(fixture,/grant usage on schema auth to anon, authenticated/);assert.match(fixture,/grant execute on function auth\.uid\(\) to anon, authenticated/);assert.ok(fixture.indexOf('create or replace function auth.uid()')<fixture.indexOf('grant usage on schema auth'))});
test('audit policy is paired with read-only authenticated table grants',()=>{assert.match(migration,/policy audit_moderator_read[\s\S]*is_taxonomy_moderator\(\)/);assert.match(migration,/grant select on public\.taxonomy_audit to authenticated/);assert.doesNotMatch(migration,/grant (?:insert|update|delete|all)[^;]*taxonomy_audit/i);for(const scenario of ['member can read taxonomy audit','admin cannot read taxonomy audit','idempotent review duplicated audit'])assert.ok(assertions.includes(scenario),`missing ${scenario}`)});
test('legacy invoker RPC compatibility runs as fixture owner with a clean identity',()=>{const compatibility=assertions.indexOf('-- Execute every Sprint 32--34 public contract'),search=assertions.indexOf('public.search_problems',compatibility),reset=assertions.lastIndexOf('reset role;',compatibility),clear=assertions.lastIndexOf("set_config('request.jwt.claim.sub','',false)",compatibility);assert.ok(compatibility>0&&reset<compatibility&&clear<compatibility&&reset<search&&clear<search);assert.match(assertions.slice(reset,search),/identity was not cleared before compatibility checks/)});
