import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import test from 'node:test';
import {NotificationRealtimeSubscription,type NotificationSignal,type SubscriptionDependencies} from '../src/repositories/notifications/realtime.ts';
import {optionalAlertEnabled} from '../src/repositories/notifications/preferences.ts';import {mergeNotificationPages,notificationPage} from '../src/repositories/notifications/pagination.ts';import type {NotificationItem,NotificationPreferences} from '../src/types/notification.ts';
import {enqueueNotificationToast,notificationToastForSignal,NotificationToastTimer} from '../src/repositories/notifications/toast.ts';
class FakeChannel{handler:(p:{new:unknown})=>void=()=>{};status:(s:string)=>void=()=>{};on(_type:string,filter:Record<string,string>,handler:(p:{new:unknown})=>void){assert.equal(filter.table,'notification_realtime_signals');assert.equal(filter.event,'INSERT');this.handler=handler;return this;}subscribe(callback:(s:any)=>void){this.status=callback;return this;}}
class FakeDocument{visibilityState:'visible'|'hidden'='visible';listener:(()=>void)|null=null;addEventListener(_n:string,l:any){this.listener=l;}removeEventListener(_n:string,l:any){if(this.listener===l)this.listener=null;}change(value:'visible'|'hidden'){this.visibilityState=value;this.listener?.();}}
function harness(){const channel=new FakeChannel();const document=new FakeDocument();let channels=0,removed=0,timers=0,cleared=0,reconciles=0;let tick=()=>{};const signals:NotificationSignal[]=[];const states:string[]=[];const client={channel(){channels++;return channel;},removeChannel(){removed++;return Promise.resolve('ok');}};const deps:SubscriptionDependencies={client:client as any,document,setInterval:((callback:()=>void)=>{timers++;tick=callback;return 10 as any}) as any,clearInterval:(()=>{cleared++;tick=()=>{};}) as any};const subscription=new NotificationRealtimeSubscription(client as any,'user-a',s=>signals.push(s),()=>{reconciles++;},s=>states.push(s),deps,60_000);return{subscription,channel,document,signals,states,tick:()=>tick(),metrics:()=>({channels,removed,timers,cleared,reconciles})};}
const item=(type:NotificationItem['type']):NotificationItem=>({id:'n',actorId:'actor',actorName:'Maria',type,title:'Alerta',message:'m',targetType:null,targetId:null,actionUrl:null,metadata:{},readAt:null,createdAt:'2026-01-01',notificationOrder:2});
test('owns one filtered subscription and handles INSERT/UPDATE signals without internal fields',()=>{const h=harness();h.subscription.start();h.subscription.start();assert.equal(h.metrics().channels,1);h.channel.status('SUBSCRIBED');for(const change_type of ['INSERT','UPDATE'] as const)h.channel.handler({new:{recipient_id:'user-a',notification_id:'n',notification_order:2,change_type}});assert.deepEqual(h.signals.map(s=>s.change_type),['INSERT','UPDATE']);assert.deepEqual(Object.keys(h.signals[0]).sort(),['change_type','notification_id','notification_order','recipient_id']);});
test('failure, hidden tab, visible recovery and healthy reconnection control one timer',()=>{const h=harness();h.subscription.start();h.document.change('hidden');h.channel.status('CHANNEL_ERROR');assert.deepEqual(h.states.slice(-1),['failed']);assert.equal(h.metrics().timers,0);h.document.change('visible');assert.equal(h.metrics().timers,1);assert.equal(h.states.at(-1),'failed');const before=h.metrics().reconciles;h.tick();assert.equal(h.metrics().reconciles,before+1);h.channel.status('TIMED_OUT');assert.equal(h.metrics().timers,1);h.channel.status('SUBSCRIBED');assert.equal(h.states.at(-1),'connected');assert.equal(h.metrics().cleared,1);assert.ok(h.metrics().reconciles>=3);});
test('logout/unmount and account replacement remove listener, timer and channel',()=>{const a=harness();a.subscription.start();a.channel.status('CLOSED');a.subscription.stop();a.subscription.stop();assert.deepEqual(a.metrics(),{channels:1,removed:1,timers:1,cleared:1,reconciles:1});assert.equal(a.document.listener,null);const b=harness();b.subscription.start();assert.equal(b.metrics().channels,1);});
test('optional preferences suppress only immediate alerts; critical alerts remain enabled',()=>{const off:NotificationPreferences={contributions:false,comments:false,favorites:false,updatedAt:''};assert.equal(optionalAlertEnabled(item('comment.created'),off),false);assert.equal(optionalAlertEnabled(item('contribution.received'),off),false);assert.equal(optionalAlertEnabled(item('favorite.content_updated'),off),false);assert.equal(optionalAlertEnabled(item('report.resolved'),off),true);assert.equal(optionalAlertEnabled(item('user.role_changed'),off),true);});
test('INSERT queues allowed and critical toasts while UPDATE and repeated ids never do',()=>{const on:NotificationPreferences={contributions:true,comments:true,favorites:true,updatedAt:''};const off={...on,comments:false};const seen=new Set<string>();const insert:NotificationSignal={recipient_id:'u',notification_id:'n',notification_order:1,change_type:'INSERT'};assert.equal(notificationToastForSignal(insert,[item('comment.created')],off,seen),null);assert.equal(notificationToastForSignal({...insert,notification_id:'critical'},[{...item('report.resolved'),id:'critical'}],off,seen)?.id,'critical');assert.equal(notificationToastForSignal({...insert,change_type:'UPDATE'},[item('comment.created')],on,seen),null);assert.equal(notificationToastForSignal(insert,[item('comment.created')],on,seen)?.id,'n');assert.equal(notificationToastForSignal(insert,[item('comment.created')],on,seen),null);});
test('simultaneous INSERT alerts queue deterministically without overwriting',()=>{const first=item('comment.created');const second={...first,id:'n2'};assert.deepEqual(enqueueNotificationToast(enqueueNotificationToast([],first),second).map(value=>value.id),['n','n2']);assert.equal(enqueueNotificationToast([first],first).length,1);});
test('toast timeout closes and unmount cleanup cancels the controlled timer',()=>{let scheduled:(()=>void)|null=null;let closed=0;let cleared=0;const timer=new NotificationToastTimer(()=>closed++,10,((callback:()=>void)=>{scheduled=callback;return 1 as any}) as any,(()=>cleared++) as any);timer.start();assert.ok(scheduled);(scheduled as unknown as ()=>void)();assert.equal(closed,1);timer.stop();assert.equal(cleared,1);});
test('official reconciliation preserves attribution, dedupe, count and pagination',()=>{const newest=item('comment.created');const older={...item('comment.created'),id:'older',notificationOrder:1};const updated={...newest,actorName:'Maria atualizada',readAt:'2026-07-30'};const merged=mergeNotificationPages([newest,older],[updated]);const page=notificationPage(merged,5);assert.equal(page.items.length,2);assert.equal(page.items[0].actorName,'Maria atualizada');assert.equal(page.items[0].readAt,'2026-07-30');assert.equal(new Set(page.items.map(x=>x.id)).size,2);const officialUnread=1;assert.equal(officialUnread,page.items.filter(x=>!x.readAt).length);});
test('SQL assertions execute isolation, cleanup and safe projection scenarios',()=>{const sql=readFileSync('scripts/fixtures/sprint45_notifications_realtime_assertions.sql','utf8');for(const scenario of ['set role anon','direct DML accepted','account A preferences leaked','cleanup scope failed','unsafe signal projection','internal notifications table was published'])assert.ok(sql.includes(scenario));});
