import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import type {SupabaseClient} from '@supabase/supabase-js';
import {parseModerationHistory,parseModerationResult,parseModerationState,SupabaseAdminModerationRepository} from '../src/repositories/adminModeration/AdminModerationRepositoryCore.ts';
import {canSubmitModeration,loadAdminModerationView,loadModerationHistory,moderationActionForStatus} from '../src/components/reports/adminModerationState.ts';
import {reportsEnUS,reportsPtBR} from '../src/i18n/locales/reports.ts';

const history={id:'a',action:'archive',reason:'reason',moderator_note:null,previous_status:'Reportado',resulting_status:'Arquivado',created_at:'2026-07-30T00:00:00Z'};
const result={id:'a',target_type:'problem',target_id:'p',action:'archive',previous_status:'Reportado',resulting_status:'Arquivado',created_at:'2026-07-30T00:00:00Z'};
const state={target_type:'problem',target_id:'p',current_status:'Reportado'};

test('strict parsers reject absent, partial and invalid state responses',()=>{assert.deepEqual(parseModerationState(state),{targetType:'problem',targetId:'p',currentStatus:'Reportado'});assert.equal(parseModerationState(null),null);assert.equal(parseModerationState({...state,current_status:undefined}),null);assert.equal(parseModerationState({...state,current_status:'made-up'}),null);assert.ok(parseModerationHistory(history));assert.equal(parseModerationHistory({...history,reason:undefined}),null);assert.ok(parseModerationResult(result));assert.equal(parseModerationResult({...result,target_id:undefined}),null);assert.equal('moderatorId' in parseModerationHistory(history)!,false)});

test('repository validates state singleton, mutation singleton and history list',async()=>{let i=0;const responses=[{data:[state],error:null},{data:[history],error:null},{data:[result],error:null},{data:[],error:null}];const client={rpc:async()=>responses[i++]} as unknown as SupabaseClient;const repo=new SupabaseAdminModerationRepository(client);assert.equal((await repo.state('problem','p')).ok,true);assert.equal((await repo.history('problem','p')).ok,true);assert.equal((await repo.moderate('problem','p','archive','r','')).ok,true);assert.equal((await repo.state('problem','p')).ok,false)});

test('unavailable repository and history errors always finish loading',async()=>{assert.deepEqual(await loadModerationHistory(null,'problem','p','unavailable'),{loading:false,items:[],error:'unavailable'});assert.deepEqual(await loadModerationHistory({history:async()=>({ok:false,message:'safe'})},'problem','p','unavailable'),{loading:false,items:[],error:'safe'});assert.deepEqual(await loadAdminModerationView(null,'problem','p','unavailable'),{loading:false,currentStatus:null,items:[],error:'unavailable'});const failed=await loadAdminModerationView({state:async()=>({ok:true,data:{targetType:'problem',targetId:'p',currentStatus:'Reportado'}}),history:async()=>({ok:false,message:'history failed'})},'problem','p','unavailable');assert.deepEqual(failed,{loading:false,currentStatus:'Reportado',items:[],error:'history failed'})});

test('successful view loading finishes and preserves server current status',async()=>{const loaded=await loadAdminModerationView({state:async()=>({ok:true,data:{targetType:'problem',targetId:'p',currentStatus:'Reportado'}}),history:async()=>({ok:true,data:[{...parseModerationHistory(history)!,action:'restore',resultingStatus:'Arquivado'}]})},'problem','p','unavailable');assert.equal(loaded.loading,false);assert.equal(loaded.currentStatus,'Reportado');assert.equal(moderationActionForStatus('problem',loaded.currentStatus!),'archive')});

test('buttons derive only from real current_status, not stale history, and double submission is blocked',()=>{assert.equal(moderationActionForStatus('problem','Arquivado'),'restore');assert.equal(moderationActionForStatus('solution','Arquivada'),'restore');assert.equal(moderationActionForStatus('problem','Reportado'),'archive');assert.equal(canSubmitModeration('reason',false),true);assert.equal(canSubmitModeration('reason',true),false);assert.equal(canSubmitModeration('  ',false),false)});

test('Sprint 43 translations exist in pt-BR and en-US',()=>{for(const key of ['reports.moderation.unavailableStatus','reports.moderation.archive','reports.moderation.restore','reports.moderation.reason'] as const){assert.equal(typeof reportsPtBR[key],'string');assert.equal(typeof reportsEnUS[key],'string');assert.notEqual(reportsPtBR[key],'');assert.notEqual(reportsEnUS[key],'')}});

test('migration and workflow carry the hardened Sprint 43 contract',()=>{const sql=readFileSync('supabase/migrations/20260730120000_sprint43_content_moderation.sql','utf8'),workflow=readFileSync('.github/workflows/deploy.yml','utf8');assert.match(sql,/action_order bigint generated always as identity unique/);assert.match(sql,/content_moderation_actions_target_idx[\s\S]*target_type,target_id,action_order/);assert.match(sql,/enable row level security[\s\S]*force row level security/);assert.match(sql,/security definer set search_path = pg_catalog, public/g);assert.match(sql,/for update/);assert.match(sql,/order by a\.action_order desc limit 1/);assert.match(sql,/order by a\.action_order asc/);assert.doesNotMatch(sql,/order by a\.created_at (?:asc|desc),a\.id (?:asc|desc)/);assert.match(sql,/v_last_action is distinct from 'archive'/);assert.match(sql,/get_content_moderation_state/);assert.ok(workflow.includes('sprint43_content_moderation_assertions.sql'))});

test('authenticated admin fixture observes reports and target state only through RPCs',()=>{const fixture=readFileSync('scripts/fixtures/sprint43_content_moderation_assertions.sql','utf8');const adminScenario=fixture.slice(fixture.indexOf("select set_config('request.jwt.claim.sub','42000000-0000-0000-0000-000000000099'"),fixture.indexOf('-- A manually archived row'));assert.match(adminScenario,/from public\.get_admin_content_reports/);assert.match(adminScenario,/from public\.get_content_moderation_state/);assert.doesNotMatch(adminScenario,/from public\.(?:content_reports|problems|solutions)\b/);assert.match(adminScenario,/is distinct from 'Arquivado'/);assert.match(adminScenario,/is distinct from v_report_status/)});
