import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import type { SupabaseClient } from '@supabase/supabase-js';
import { loadMyContentReports } from '../src/components/reports/myContentReportsState.ts';
import { parseAdminContentReport, parseCreatedContentReport, parseModeratedContentReport, parseMyContentReport, SupabaseContentReportRepository } from '../src/repositories/contentReports/ContentReportRepositoryCore.ts';

const base={id:'report-1',target_type:'problem',target_id:'target-1',reason:'spam',status:'open'};
const created={...base,created_at:'2026-07-29T00:00:00Z'};
const mine={...created,description:null,updated_at:'2026-07-29T00:00:01Z'};
const admin={...mine,target_title:'Target',moderator_note:null,reviewed_at:null,total_count:'2'};
const moderated={id:'report-1',status:'resolved',updated_at:'2026-07-29T00:01:00Z',reviewed_at:'2026-07-29T00:01:00Z'};
function client(responses:Array<{data:unknown;error:unknown}>) { let index=0;return {rpc:async()=>responses[index++]} as unknown as SupabaseClient; }

test('each RPC format has a dedicated strict parser',()=>{assert.deepEqual(parseCreatedContentReport(created),{id:'report-1',targetType:'problem',targetId:'target-1',reason:'spam',status:'open',createdAt:created.created_at});assert.equal(parseCreatedContentReport({...created,target_id:undefined}),null);assert.equal(parseCreatedContentReport(null),null);assert.equal(parseMyContentReport({...mine,description:undefined}),null);assert.equal(parseAdminContentReport(admin)?.totalCount,2);assert.equal(parseAdminContentReport({...admin,moderator_note:undefined}),null);assert.deepEqual(parseModeratedContentReport(moderated),{id:'report-1',status:'resolved',updatedAt:moderated.updated_at,reviewedAt:moderated.reviewed_at});assert.equal(parseModeratedContentReport({...moderated,updated_at:undefined}),null)});

test('create and moderate accept only one valid response row',async()=>{const repository=new SupabaseContentReportRepository(client([{data:[created],error:null},{data:[moderated],error:null},{data:[],error:null}]));const create=await repository.create('problem','target-1','spam','');assert.equal(create.ok,true);const moderate=await repository.moderate('report-1','resolved','ok');assert.equal(moderate.ok,true);const empty=await repository.create('problem','target-1','spam','');assert.deepEqual(empty,{ok:false,message:'O servidor retornou uma resposta de denúncia inválida.'})});

test('my and admin lists reject malformed responses and preserve pagination parameters',async()=>{const calls:Array<Record<string,unknown>>=[];const fake = { rpc: async (_name:string,args?:Record<string,unknown>) => { calls.push(args??{}); return calls.length===1 ? {data:[mine],error:null} : calls.length===2 ? {data:[admin],error:null} : {data:[{...mine,target_id:undefined}],error:null}; } } as unknown as SupabaseClient;const repository=new SupabaseContentReportRepository(fake);const my=await repository.listMine();assert.equal(my.ok,true);const page=await repository.listAdmin({page:2,limit:20,status:'open'});assert.equal(page.ok,true);assert.equal(page.ok&&page.data.total,2);assert.equal(calls[1].p_offset,40);const invalid=await repository.listMine();assert.equal(invalid.ok,false)});

test('public objects never contain reporter or moderator identities',()=>{for(const parsed of [parseCreatedContentReport(created),parseMyContentReport(mine),parseAdminContentReport(admin),parseModeratedContentReport(moderated)]){assert.ok(parsed);assert.equal('reporterId' in parsed,false);assert.equal('moderatorId' in parsed,false);assert.doesNotMatch(JSON.stringify(parsed),/undefined/)}});

test('my reports loader always ends loading with safe unavailable and repository errors',async()=>{assert.deepEqual(await loadMyContentReports(null,'Indisponível'),{loading:false,items:[],error:'Indisponível'});assert.deepEqual(await loadMyContentReports({listMine:async()=>({ok:false,message:'Falha segura'})},'Indisponível'),{loading:false,items:[],error:'Falha segura'});assert.deepEqual(await loadMyContentReports({listMine:async()=>({ok:true,data:[]})},'Indisponível'),{loading:false,items:[],error:''})});

test('isolated PostgreSQL installs the production-compatible admin contract before Sprint 42',()=>{const compatibility=readFileSync('scripts/fixtures/sprint42_admin_compatibility.sql','utf8');const migration=readFileSync('supabase/migrations/20260729140000_sprint42_content_reports.sql','utf8');const workflow=readFileSync('.github/workflows/deploy.yml','utf8');assert.match(compatibility,/auth\.uid\(\)[\s\S]*public\.profiles[\s\S]*role = 'admin'/);assert.match(compatibility,/security definer[\s\S]*search_path = pg_catalog, public/i);assert.doesNotMatch(compatibility,/\(p?_?user_id uuid\)/i);assert.match(migration,/to_regprocedure\('public\.is_admin\(\)'\)[\s\S]*requires public\.is_admin/);assert.ok(workflow.indexOf('sprint42_admin_compatibility.sql')<workflow.indexOf('20260729140000_sprint42_content_reports.sql'))});
