import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { NotificationToast } from '../components/notifications/NotificationToast';
import { useAuth } from '../hooks/useAuth';
import { supabaseClient } from '../integrations/supabase/client';
import { NotificationRepository } from '../repositories/notifications';
import { NotificationRealtimeSubscription, type ConnectionState, type NotificationSignal } from '../repositories/notifications/realtime';
import { enqueueNotificationToast, notificationToastForSignal } from '../repositories/notifications/toast';
import type { NotificationItem, NotificationPreferences } from '../types/notification';

interface Value { recentItems:NotificationItem[];unreadCount:number;loading:boolean;busy:boolean;error:string;readAtById:Record<string,string>;allReadAt:string|null;connectionState:ConnectionState;revision:number;announcement:string;reload:()=>Promise<void>;markRead:(id:string)=>Promise<boolean>;markAllRead:()=>Promise<boolean> }
interface State { userId:string|null;items:NotificationItem[];count:number;preferences:NotificationPreferences;loading:boolean;busy:boolean;error:string;connection:ConnectionState;revision:number;announcement:string;toasts:NotificationItem[] }
const defaults:NotificationPreferences={contributions:true,comments:true,favorites:true,updatedAt:''};
const initial:State={userId:null,items:[],count:0,preferences:defaults,loading:false,busy:false,error:'',connection:'connecting',revision:0,announcement:'',toasts:[]};
type Action={type:'reset';userId:string|null}|{type:'loading';userId:string}|{type:'loaded';userId:string;items:NotificationItem[];count:number;preferences:NotificationPreferences}|{type:'error';userId:string;message:string}|{type:'busy';userId:string;value:boolean}|{type:'connection';value:ConnectionState}|{type:'toast';item:NotificationItem}|{type:'dismiss'}|{type:'preferences';value:NotificationPreferences};
function reducer(state:State,action:Action):State { switch(action.type){case'reset':return{...initial,userId:action.userId,loading:Boolean(action.userId)};case'loading':return state.userId===action.userId?{...state,loading:true,error:''}:state;case'loaded':return state.userId===action.userId?{...state,items:action.items,count:action.count,preferences:action.preferences,loading:false,error:'',revision:state.revision+1}:state;case'error':return state.userId===action.userId?{...state,loading:false,error:action.message}:state;case'busy':return state.userId===action.userId?{...state,busy:action.value}:state;case'connection':return{...state,connection:action.value};case'toast':return{...state,announcement:action.item.title,toasts:enqueueNotificationToast(state.toasts,action.item)};case'dismiss':return{...state,announcement:'',toasts:state.toasts.slice(1)};case'preferences':return{...state,preferences:action.value};} }
const Context=createContext<Value|undefined>(undefined);

export function NotificationsProvider({children}:{children:ReactNode}) {
  const {isAuthenticated,user}=useAuth();const userId=isAuthenticated?user?.id??null:null;
  const [state,setState]=useState<State>(initial);const dispatch=useCallback((action:Action)=>setState(current=>reducer(current,action)),[]);
  const active=useRef(userId);active.current=userId;const generation=useRef(0);const operation=useRef(0);const busyRef=useRef(false);const chain=useRef<Promise<void>>(Promise.resolve());const alerted=useRef(new Set<string>());
  const reconcile=useCallback(async(account:string,signal?:NotificationSignal)=>{if(!NotificationRepository)return;dispatch({type:'loading',userId:account});try{const [listed,counted,prefs]=await Promise.all([NotificationRepository.list({limit:5}),NotificationRepository.getUnreadCount(),NotificationRepository.getPreferences()]);if(active.current!==account)return;if(!listed.ok){dispatch({type:'error',userId:account,message:listed.message});return;}if(!counted.ok){dispatch({type:'error',userId:account,message:counted.message});return;}if(!prefs.ok){dispatch({type:'error',userId:account,message:prefs.message});return;}dispatch({type:'loaded',userId:account,items:listed.data.items,count:counted.data,preferences:prefs.data});const toast=notificationToastForSignal(signal,listed.data.items,prefs.data,alerted.current);if(toast)dispatch({type:'toast',item:toast});}catch{if(active.current===account)dispatch({type:'error',userId:account,message:'Não foi possível carregar as notificações.'});}},[]);
  const schedule=useCallback((signal?:NotificationSignal)=>{const account=userId;if(!account)return Promise.resolve();const task=chain.current.catch(()=>undefined).then(()=>reconcile(account,signal));chain.current=task;return task;},[reconcile,userId]);
  const reload=useCallback(()=>schedule(),[schedule]);
  useEffect(()=>{generation.current++;operation.current++;busyRef.current=false;chain.current=Promise.resolve();alerted.current.clear();dispatch({type:'reset',userId});if(userId)void schedule();return()=>{generation.current++;operation.current++;busyRef.current=false;alerted.current.clear();};},[schedule,userId]);
  useEffect(()=>{const changed=(event:Event)=>dispatch({type:'preferences',value:(event as CustomEvent<NotificationPreferences>).detail});window.addEventListener('notification-preferences-changed',changed);return()=>window.removeEventListener('notification-preferences-changed',changed);},[]);
  useEffect(()=>{if(!userId||!supabaseClient)return;const subscription=new NotificationRealtimeSubscription(supabaseClient,userId,signal=>{if(active.current===userId)void schedule(signal);},reload,value=>dispatch({type:'connection',value}));subscription.start();return()=>subscription.stop();},[reload,schedule,userId]);
  const markRead=useCallback(async(id:string)=>{if(!userId||!NotificationRepository||busyRef.current)return false;const account=userId;const token=++operation.current;busyRef.current=true;dispatch({type:'busy',userId:account,value:true});try{const result=await NotificationRepository.markRead(id);if(active.current!==account||token!==operation.current)return false;if(!result.ok){dispatch({type:'error',userId:account,message:result.message});return false;}await schedule();return true;}catch{return false;}finally{if(token===operation.current){busyRef.current=false;dispatch({type:'busy',userId:account,value:false});}}},[schedule,userId]);
  const markAllRead=useCallback(async()=>{if(!userId||!NotificationRepository||busyRef.current)return false;const account=userId;const token=++operation.current;busyRef.current=true;dispatch({type:'busy',userId:account,value:true});try{const result=await NotificationRepository.markAllRead();if(active.current!==account||token!==operation.current)return false;if(!result.ok){dispatch({type:'error',userId:account,message:result.message});return false;}await schedule();return true;}catch{return false;}finally{if(token===operation.current){busyRef.current=false;dispatch({type:'busy',userId:account,value:false});}}},[schedule,userId]);
  const valid=state.userId===userId&&Boolean(userId);const dismiss=useCallback(()=>dispatch({type:'dismiss'}),[]);
  const value=useMemo<Value>(()=>({recentItems:valid?state.items:[],unreadCount:valid?state.count:0,loading:valid?state.loading:Boolean(userId),busy:valid?state.busy:false,error:valid?state.error:'',readAtById:{},allReadAt:null,connectionState:state.connection,revision:state.revision,announcement:valid?state.announcement:'',reload,markRead,markAllRead}),[markAllRead,markRead,reload,state,userId,valid]);
  return <Context.Provider value={value}>{children}<NotificationToast notification={valid?state.toasts[0]??null:null} onClose={dismiss}/></Context.Provider>;
}
export function useNotificationsContext():Value { const value=useContext(Context) as Value|undefined;if(!value)throw new Error('useNotificationsContext deve ser usado dentro de NotificationsProvider.');return value; }
