import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {useAuth} from '../hooks/useAuth';
import {NotificationRepository} from '../repositories/notifications';
import {NotificationRealtimeSubscription,type ConnectionState,type NotificationSignal} from '../repositories/notifications/realtime';
import {supabaseClient} from '../integrations/supabase/client';
import type {NotificationItem,NotificationPreferences} from '../types/notification';
import {optionalAlertEnabled} from '../repositories/notifications/preferences';

interface Value{recentItems:NotificationItem[];unreadCount:number;loading:boolean;busy:boolean;error:string;readAtById:Record<string,string>;allReadAt:string|null;connectionState:ConnectionState;revision:number;announcement:string;reload:()=>Promise<void>;markRead:(id:string)=>Promise<boolean>;markAllRead:()=>Promise<boolean>}
interface State{userId:string|null;items:NotificationItem[];count:number;preferences:NotificationPreferences;loading:boolean;busy:boolean;error:string;connection:ConnectionState;revision:number;announcement:string}
const defaults:NotificationPreferences={contributions:true,comments:true,favorites:true,updatedAt:''};
const initial:State={userId:null,items:[],count:0,preferences:defaults,loading:false,busy:false,error:'',connection:'connecting',revision:0,announcement:''};
type Action={type:'reset';userId:string|null}|{type:'loading';userId:string}|{type:'loaded';userId:string;items:NotificationItem[];count:number;preferences:NotificationPreferences}|{type:'error';userId:string;message:string}|{type:'busy';value:boolean}|{type:'connection';value:ConnectionState}|{type:'announce';value:string}|{type:'preferences';value:NotificationPreferences};
function reducer(state:State,action:Action):State{switch(action.type){case'reset':return{...initial,userId:action.userId,loading:Boolean(action.userId)};case'loading':return state.userId===action.userId?{...state,loading:true,error:''}:state;case'loaded':return state.userId===action.userId?{...state,items:action.items,count:action.count,preferences:action.preferences,loading:false,error:'',revision:state.revision+1}:state;case'error':return state.userId===action.userId?{...state,loading:false,error:action.message}:state;case'busy':return{...state,busy:action.value};case'connection':return{...state,connection:action.value};case'announce':return{...state,announcement:action.value};case'preferences':return{...state,preferences:action.value};}}
const Context=createContext<Value|undefined>(undefined);
export function NotificationsProvider({children}:{children:ReactNode}){
 const {isAuthenticated,user}=useAuth();const userId=isAuthenticated?user?.id??null:null;const [state,setState]=useState<State>(initial);const dispatch=useCallback((action:Action)=>setState(current=>reducer(current,action)),[]);const active=useRef(userId);active.current=userId;const request=useRef(0);const busy=useRef(false);const pendingSignal=useRef<NotificationSignal|null>(null);
 const reload=useCallback(async()=>{const account=userId;if(!account||!NotificationRepository)return;const token=++request.current;dispatch({type:'loading',userId:account});const [listed,counted,prefs]=await Promise.all([NotificationRepository.list({limit:5}),NotificationRepository.getUnreadCount(),NotificationRepository.getPreferences()]);if(active.current!==account||token!==request.current)return;if(!listed.ok){dispatch({type:'error',userId:account,message:listed.message});return;}if(!counted.ok){dispatch({type:'error',userId:account,message:counted.message});return;}if(!prefs.ok){dispatch({type:'error',userId:account,message:prefs.message});return;}dispatch({type:'loaded',userId:account,items:listed.data.items,count:counted.data,preferences:prefs.data});const signal=pendingSignal.current;pendingSignal.current=null;if(signal){const item=listed.data.items.find(x=>x.id===signal.notification_id);dispatch({type:'announce',value:item&&optionalAlertEnabled(item,prefs.data)?item.title:''});}},[userId]);
 useEffect(()=>{request.current++;pendingSignal.current=null;dispatch({type:'reset',userId});if(userId)void reload();return()=>{request.current++;};},[reload,userId]);
 useEffect(()=>{const changed=(event:Event)=>{const detail=(event as CustomEvent<NotificationPreferences>).detail;dispatch({type:'preferences',value:detail});};window.addEventListener('notification-preferences-changed',changed);return()=>window.removeEventListener('notification-preferences-changed',changed);},[]);
 useEffect(()=>{if(!userId||!supabaseClient)return;const subscription=new NotificationRealtimeSubscription(supabaseClient,userId,signal=>{if(active.current!==userId)return;pendingSignal.current=signal;void reload();},reload,value=>dispatch({type:'connection',value}));subscription.start();return()=>subscription.stop();},[reload,userId]);
 const markRead=useCallback(async(id:string)=>{if(!userId||!NotificationRepository||busy.current)return false;const account=userId;busy.current=true;dispatch({type:'busy',value:true});const result=await NotificationRepository.markRead(id);if(active.current!==account)return false;busy.current=false;dispatch({type:'busy',value:false});if(!result.ok){dispatch({type:'error',userId:account,message:result.message});return false;}await reload();return true;},[reload,userId]);
 const markAllRead=useCallback(async()=>{if(!userId||!NotificationRepository||busy.current)return false;const account=userId;busy.current=true;dispatch({type:'busy',value:true});const result=await NotificationRepository.markAllRead();if(active.current!==account)return false;busy.current=false;dispatch({type:'busy',value:false});if(!result.ok){dispatch({type:'error',userId:account,message:result.message});return false;}await reload();return true;},[reload,userId]);
 const valid=state.userId===userId&&Boolean(userId);const value=useMemo<Value>(()=>({recentItems:valid?state.items:[],unreadCount:valid?state.count:0,loading:valid?state.loading:Boolean(userId),busy:state.busy,error:valid?state.error:'',readAtById:{},allReadAt:null,connectionState:state.connection,revision:state.revision,announcement:state.announcement,reload,markRead,markAllRead}),[markAllRead,markRead,reload,state,userId,valid]);
 return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useNotificationsContext():Value{const value=useContext(Context) as Value|undefined;if(!value)throw new Error('useNotificationsContext deve ser usado dentro de NotificationsProvider.');return value;}
