export const contentPtBR = {
  'about.title':'Sobre o Banco de Soluções','about.intro':'O Banco de Soluções organiza conhecimento prático sobre desafios reais. Em vez de armazenar ideias isoladas, a plataforma conecta problemas, evidências, soluções, pessoas, empresas e projetos em uma rede aberta.','about.community':'Aqui, a comunidade pode compartilhar experiências, encontrar iniciativas e colaborar para transformar conhecimento em ação.','about.proposal':'Nossa proposta','about.visibility':'Dar visibilidade a problemas e ideias que podem gerar impacto.','about.connect':'Conectar desafios a soluções e evidências compartilhadas.','about.collaborate':'Fortalecer a colaboração entre pessoas e organizações.',
  'favorites.title':'Meus Favoritos','favorites.description':'Acesse rapidamente os problemas e soluções que você marcou como favoritos na sua conta.','favorites.loading':'Carregando favoritos','favorites.loadingMessage':'Buscando seus favoritos...','favorites.empty':'Nenhum favorito ainda','favorites.emptyMessage':'Favorite problemas e soluções para encontrá-los nesta página.','favorites.problems':'Problemas favoritados','favorites.solutions':'Soluções favoritadas','favorites.noProblem':'Nenhum problema favoritado','favorites.noProblemMessage':'Marque problemas como favoritos para vê-los aqui.','favorites.noSolution':'Nenhuma solução favoritada','favorites.noSolutionMessage':'Marque soluções como favoritas para vê-las aqui.','count.item.one':'item','count.item.other':'itens',
  'card.problemImage':'Imagem do problema {{title}}','card.solutionImage':'Imagem da solução {{title}}','card.removeFavorite':'Remover {{title}} dos favoritos','card.addFavorite':'Adicionar {{title}} aos favoritos','card.verifiedSource':'Fonte externa verificada','card.originalSource':'Consultar fonte original','card.details':'Ver detalhes','metric.likes':'curtidas','metric.comments':'comentários','metric.views':'visualizações',
  'pagination.label':'Paginação','pagination.summary':'Mostrando {{start}}–{{end}} de {{total}} resultados.','pagination.previous':'Anterior','pagination.next':'Próxima','pagination.previousA11y':'Ir para a página anterior','pagination.nextA11y':'Ir para a próxima página','pagination.pageA11y':'Ir para a página {{page}}',
} as const;
export const contentEnUS = {
  'about.title':'About Solution Bank','about.intro':'Solution Bank organizes practical knowledge about real challenges. Instead of storing isolated ideas, the platform connects problems, evidence, solutions, people, companies, and projects in an open network.','about.community':'Here, the community can share experiences, find initiatives, and collaborate to turn knowledge into action.','about.proposal':'Our mission','about.visibility':'Give visibility to problems and ideas that can create impact.','about.connect':'Connect challenges to shared solutions and evidence.','about.collaborate':'Strengthen collaboration between people and organizations.',
  'favorites.title':'My Favorites','favorites.description':'Quickly access the problems and solutions you marked as favorites in your account.','favorites.loading':'Loading favorites','favorites.loadingMessage':'Fetching your favorites...','favorites.empty':'No favorites yet','favorites.emptyMessage':'Favorite problems and solutions to find them on this page.','favorites.problems':'Favorite problems','favorites.solutions':'Favorite solutions','favorites.noProblem':'No favorite problems','favorites.noProblemMessage':'Mark problems as favorites to see them here.','favorites.noSolution':'No favorite solutions','favorites.noSolutionMessage':'Mark solutions as favorites to see them here.','count.item.one':'item','count.item.other':'items',
  'card.problemImage':'Image for problem {{title}}','card.solutionImage':'Image for solution {{title}}','card.removeFavorite':'Remove {{title}} from favorites','card.addFavorite':'Add {{title}} to favorites','card.verifiedSource':'Verified external source','card.originalSource':'View original source','card.details':'View details','metric.likes':'likes','metric.comments':'comments','metric.views':'views',
  'pagination.label':'Pagination','pagination.summary':'Showing {{start}}–{{end}} of {{total}} results.','pagination.previous':'Previous','pagination.next':'Next','pagination.previousA11y':'Go to previous page','pagination.nextA11y':'Go to next page','pagination.pageA11y':'Go to page {{page}}',
} as const;
