export const sharedPtBR = {
 'toolbar.search':'Pesquisar','toolbar.sort':'Ordenação','toolbar.all':'Todos','toolbar.favoritesOnly':'Somente favoritos','toolbar.clear':'Limpar filtros',
 'mfa.title':'Confirme sua identidade','mfa.description':'Digite o código gerado pelo seu aplicativo autenticador.','mfa.verifying':'Verificando…','mfa.confirm':'Confirmar código','common.retry':'Tentar novamente','mfa.leave':'Sair e voltar ao login','admin.checking':'Verificando permissões…','admin.error403':'Erro 403','admin.forbidden':'Acesso não autorizado','admin.forbiddenDescription':'Sua conta não possui permissão para acessar a área administrativa.',
 'auth.required':'Autenticação necessária','auth.continue':'Entre ou crie uma conta para continuar','auth.signIn':'Entrar','auth.createAccount':'Criar conta','common.back':'Voltar','auth.checking':'Verificando sua sessão...','auth.redirecting':'Redirecionando para entrar...',
} as const;
export const sharedEnUS = {
 'toolbar.search':'Search','toolbar.sort':'Sort order','toolbar.all':'All','toolbar.favoritesOnly':'Favorites only','toolbar.clear':'Clear filters',
 'mfa.title':'Confirm your identity','mfa.description':'Enter the code generated by your authenticator app.','mfa.verifying':'Verifying…','mfa.confirm':'Confirm code','common.retry':'Try again','mfa.leave':'Sign out and return to sign in','admin.checking':'Checking permissions…','admin.error403':'Error 403','admin.forbidden':'Unauthorized access','admin.forbiddenDescription':'Your account does not have permission to access the administration area.',
 'auth.required':'Authentication required','auth.continue':'Sign in or create an account to continue','auth.signIn':'Sign in','auth.createAccount':'Create account','common.back':'Back','auth.checking':'Checking your session...','auth.redirecting':'Redirecting to sign in...',
} as const;
