import { useState } from 'react';
import { Share2, X, UsersRound } from 'lucide-react';
import type { Comment, CommentReactionSummary, CommentReactionType, UserReputation } from '../../types/discussion';
import { CommentEditor } from './CommentEditor';
import { ReactionBar } from './ReactionBar';
import { useTranslation } from '../../i18n/I18nProvider';
import { formatDateTime } from '../../i18n/format';
type ActionResult = { ok: boolean; message?: string }; type MaybePromise<T> = T | Promise<T>;
export function CommentCard({ comment, reputation, currentUserId, reactionSummary, pendingReactions, onToggleReaction, onEdit, onDelete }: { comment: Comment; reputation?: UserReputation; currentUserId: string | null; reactionSummary: CommentReactionSummary; pendingReactions: CommentReactionType[]; onToggleReaction: (commentId: string, type: CommentReactionType) => Promise<ActionResult>; onEdit: (commentId: string, content: string) => MaybePromise<ActionResult>; onDelete: (commentId: string) => MaybePromise<ActionResult> }) {
 const { locale,t }=useTranslation(); const [editing,setEditing]=useState(false); const [message,setMessage]=useState(''); const [deleting,setDeleting]=useState(false); const isAuthor=currentUserId===comment.authorId;
 const remove=async()=>{if(deleting||!window.confirm(t('comment.deleteConfirm')))return;setDeleting(true);const result=await onDelete(comment.id);setMessage(result.ok?t('comment.deleted'):result.message??t('comment.deleteFailed'));setDeleting(false);};
 const toggle=async(type:CommentReactionType)=>{const result=await onToggleReaction(comment.id,type);setMessage(result.ok?t('reaction.updated'):result.message??t('reaction.error'));return result;};
 return <article className="rounded-3xl border border-line bg-white p-5"><header className="flex items-center gap-3">{comment.authorAvatarUrl?<img src={comment.authorAvatarUrl} alt="" className="h-10 w-10 rounded-full object-cover"/>:<span className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><UsersRound size={20}/></span>}<div><h3 className="font-semibold">{comment.authorName}</h3>{reputation&&<div className="flex flex-wrap items-center gap-1 text-xs font-medium text-teal-700" aria-label={t('reputation.authorSummary',{points:reputation.points,badges:reputation.badges.length})}><span>{t('reputation.compact',{points:reputation.points,badges:reputation.badges.length})}</span>{reputation.badges.map(badge=><span key={badge.id} title={t(`reputation.achievement.${badge.id}.description`)} className="rounded-full bg-teal-50 px-2 py-0.5">{t(`reputation.achievement.${badge.id}.title`)}</span>)}</div>}<p className="text-xs text-muted">{formatDateTime(comment.createdAt,locale)}{comment.edited?` · ${t('comment.edited')}`:''}</p></div></header>
 {editing?<div className="mt-4"><CommentEditor initialValue={comment.content} submitLabel={t('comment.saveEdit')} onSubmit={async(content)=>{const result=await onEdit(comment.id,content);if(result.ok)setEditing(false);return result;}}/></div>:<p className="mt-4 whitespace-pre-line leading-7 text-slate-700">{comment.content}</p>}
 <div className="mt-4"><ReactionBar summary={reactionSummary} currentUserId={currentUserId} pending={pendingReactions} onToggle={toggle}/></div>{!currentUserId&&<p className="mt-2 text-xs text-muted">{t('reaction.signIn')}</p>}
 {isAuthor&&<div className="mt-4 flex gap-2"><button type="button" disabled={deleting} onClick={()=>setEditing(v=>!v)} className="inline-flex items-center gap-1 rounded-full border border-line px-3 py-1.5 text-xs font-semibold"><Share2 size={14}/> {t('common.edit')}</button><button type="button" disabled={deleting} onClick={remove} className="inline-flex items-center gap-1 rounded-full border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700"><X size={14}/> {deleting?t('common.deleting'):t('common.delete')}</button></div>}
 {message&&<p aria-live="polite" className="mt-3 text-sm font-semibold text-slate-700">{message}</p>}</article>;
}
