import type { SupabaseClient } from '@supabase/supabase-js';
import { supabaseClient } from '../../integrations/supabase/client';
import type { ImplementationDifficulty, Solution, SolutionCategory, SolutionMaturityLevel, SolutionStatus } from '../../types/domain';
import type { RepositoryResult } from '../problems/ProblemRepository';

export type SolutionRow = {
  id: string; problem_id: string; title: string; summary: string; description: string; category: string; image_url: string | null; organization: string; author_id: string; author_name: string | null; status: string; maturity_level: string; implementation_difficulty: string; estimated_cost: string | null; implementation_time: string | null; location: string; country: string; impact_metric: string; likes: number | null; comments: number | null; views: number | null; related_problem_ids: string[] | null; tags: string[] | null; evidence_links: string[] | null; created_at: string; updated_at: string;
};
export type SolutionInput = Pick<Solution, 'title' | 'summary' | 'description' | 'category' | 'organization' | 'status' | 'maturityLevel' | 'implementationDifficulty' | 'estimatedCost' | 'implementationTime' | 'location' | 'country' | 'impactMetric' | 'tags' | 'evidenceLinks' | 'relatedProblemIds'> & { image?: string; authorId: string; author?: string };
const selectColumns = 'id,problem_id,title,summary,description,category,image_url,organization,author_id,author_name,status,maturity_level,implementation_difficulty,estimated_cost,implementation_time,location,country,impact_metric,likes,comments,views,related_problem_ids,tags,evidence_links,created_at,updated_at';
const fallbackImage = 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80';
const categories: SolutionCategory[] = ['Infraestrutura', 'Educação', 'Saúde', 'Segurança', 'Tecnologia', 'Mobilidade', 'Meio Ambiente', 'Assistência Social', 'Empreendedorismo', 'Outros'];
const statuses: SolutionStatus[] = ['Proposta', 'Em teste', 'Implementada', 'Validada', 'Arquivada'];
const maturities: SolutionMaturityLevel[] = ['Ideia', 'Protótipo', 'Piloto', 'Em operação', 'Escalável'];
const difficulties: ImplementationDifficulty[] = ['Baixa', 'Média', 'Alta'];
const safe = <T extends string>(value: string, allowed: readonly T[], fallback: T) => allowed.includes(value as T) ? value as T : fallback;
function errorMessage(error: unknown, fallback: string) { return error && typeof error === 'object' && 'message' in error && typeof error.message === 'string' ? error.message : fallback; }

export function mapSolutionRowToDomain(row: SolutionRow): Solution {
  const relatedProblemIds = row.related_problem_ids?.length ? row.related_problem_ids : [row.problem_id];
  return { id: row.id, title: row.title, summary: row.summary, description: row.description, category: safe(row.category, categories, 'Outros'), image: row.image_url || fallbackImage, organization: row.organization, author: row.author_name || 'Autor não informado', createdAt: row.created_at, updatedAt: row.updated_at, status: safe(row.status, statuses, 'Proposta'), maturityLevel: safe(row.maturity_level, maturities, 'Ideia'), implementationDifficulty: safe(row.implementation_difficulty, difficulties, 'Baixa'), estimatedCost: row.estimated_cost || 'Não informado', implementationTime: row.implementation_time || 'Não informado', location: row.location, country: row.country, impactMetric: row.impact_metric, likes: row.likes ?? 0, comments: row.comments ?? 0, views: row.views ?? 0, relatedProblemIds, tags: row.tags ?? [], evidenceLinks: row.evidence_links ?? [] };
}

export class SupabaseSolutionRepository {
  constructor(private readonly client: SupabaseClient) {}
  async list(): Promise<RepositoryResult<Solution[]>> { const { data, error } = await this.client.from('solutions').select(selectColumns).order('created_at', { ascending: false }); if (error) return { ok: false, message: errorMessage(error, 'Não foi possível listar soluções.') }; return { ok: true, data: (data ?? []).map((row: unknown) => mapSolutionRowToDomain(row as SolutionRow)) }; }
  async listByProblemId(problemId: string): Promise<RepositoryResult<Solution[]>> { const { data, error } = await this.client.from('solutions').select(selectColumns).contains('related_problem_ids', [problemId]).order('created_at', { ascending: false }); if (error) return { ok: false, message: errorMessage(error, 'Não foi possível listar soluções do problema.') }; return { ok: true, data: (data ?? []).map((row: unknown) => mapSolutionRowToDomain(row as SolutionRow)) }; }
  async findById(id: string): Promise<RepositoryResult<Solution | null>> { const { data, error } = await this.client.from('solutions').select(selectColumns).eq('id', id).maybeSingle(); if (error) return { ok: false, message: errorMessage(error, 'Não foi possível carregar a solução.') }; return { ok: true, data: data ? mapSolutionRowToDomain(data as SolutionRow) : null }; }
  async create(input: SolutionInput): Promise<RepositoryResult<Solution>> { const problemId = input.relatedProblemIds[0]; const { data, error } = await this.client.from('solutions').insert({ problem_id: problemId, title: input.title.trim(), summary: input.summary.trim(), description: input.description.trim(), category: input.category, image_url: input.image?.trim() || null, organization: input.organization.trim(), author_id: input.authorId, author_name: input.author?.trim() || null, status: input.status, maturity_level: input.maturityLevel, implementation_difficulty: input.implementationDifficulty, estimated_cost: input.estimatedCost.trim() || null, implementation_time: input.implementationTime.trim() || null, location: input.location.trim(), country: input.country.trim(), impact_metric: input.impactMetric.trim(), related_problem_ids: input.relatedProblemIds, tags: input.tags, evidence_links: input.evidenceLinks }).select(selectColumns).single(); if (error) return { ok: false, message: errorMessage(error, 'Não foi possível criar a solução.') }; return { ok: true, data: mapSolutionRowToDomain(data as SolutionRow) }; }
  async update(id: string, input: Partial<SolutionInput>): Promise<RepositoryResult<Solution>> { const payload: Record<string, unknown> = {}; if (input.relatedProblemIds !== undefined) { payload.problem_id = input.relatedProblemIds[0]; payload.related_problem_ids = input.relatedProblemIds; } if (input.title !== undefined) payload.title = input.title.trim(); if (input.summary !== undefined) payload.summary = input.summary.trim(); if (input.description !== undefined) payload.description = input.description.trim(); if (input.category !== undefined) payload.category = input.category; if (input.image !== undefined) payload.image_url = input.image.trim() || null; if (input.organization !== undefined) payload.organization = input.organization.trim(); if (input.author !== undefined) payload.author_name = input.author.trim() || null; if (input.status !== undefined) payload.status = input.status; if (input.maturityLevel !== undefined) payload.maturity_level = input.maturityLevel; if (input.implementationDifficulty !== undefined) payload.implementation_difficulty = input.implementationDifficulty; if (input.estimatedCost !== undefined) payload.estimated_cost = input.estimatedCost.trim() || null; if (input.implementationTime !== undefined) payload.implementation_time = input.implementationTime.trim() || null; if (input.location !== undefined) payload.location = input.location.trim(); if (input.country !== undefined) payload.country = input.country.trim(); if (input.impactMetric !== undefined) payload.impact_metric = input.impactMetric.trim(); if (input.tags !== undefined) payload.tags = input.tags; if (input.evidenceLinks !== undefined) payload.evidence_links = input.evidenceLinks; const { data, error } = await this.client.from('solutions').update(payload).eq('id', id).select(selectColumns).single(); if (error) return { ok: false, message: errorMessage(error, 'Não foi possível atualizar a solução.') }; return { ok: true, data: mapSolutionRowToDomain(data as SolutionRow) }; }
  async delete(id: string): Promise<RepositoryResult<null>> { const { error } = await this.client.from('solutions').delete().eq('id', id); if (error) return { ok: false, message: errorMessage(error, 'Não foi possível excluir a solução.') }; return { ok: true, data: null }; }
}
export const SolutionRepository = supabaseClient ? new SupabaseSolutionRepository(supabaseClient) : null;
