import type { SupabaseClient } from '@supabase/supabase-js';
import { supabaseClient } from '../../integrations/supabase/client';
import { safeDatabaseMessage } from '../errors';
import type { TaxonomyKind, TaxonomyProposal, TaxonomyProposalStatus, TaxonomyScope, TaxonomyTerm } from '../../types/taxonomy';
const proposal=(row:Record<string,unknown>):TaxonomyProposal=>({id:String(row.id),proposedName:String(row.proposed_name),normalizedName:String(row.normalized_name),kind:row.kind as TaxonomyKind,scope:row.scope as TaxonomyScope,justification:String(row.justification),authorId:String(row.author_id),status:row.status as TaxonomyProposalStatus,reviewerId:row.reviewer_id?String(row.reviewer_id):null,decisionReason:row.decision_reason?String(row.decision_reason):null,createdAt:String(row.created_at),reviewedAt:row.reviewed_at?String(row.reviewed_at):null});
export class SupabaseTaxonomyRepository {
 constructor(private client:SupabaseClient){}
 async list(kind:TaxonomyKind,scope:TaxonomyScope,query='',offset=0){const {data,error}=await this.client.rpc('list_taxonomy_terms',{p_kind:kind,p_scope:scope,p_query:query,p_limit:100,p_offset:offset});if(error)return {ok:false as const,message:safeDatabaseMessage(error,'Não foi possível carregar a taxonomia.')};const items:TaxonomyTerm[]=(data??[]).map((r:Record<string,unknown>)=>({id:String(r.id),kind:r.kind as TaxonomyKind,scope:r.scope as TaxonomyScope,name:String(r.name),slug:String(r.slug),totalCount:Number(r.total_count)}));return {ok:true as const,data:{items,total:items[0]?.totalCount??0}}}
 async propose(name:string,kind:TaxonomyKind,scope:TaxonomyScope,justification:string){const {data,error}=await this.client.rpc('submit_taxonomy_proposal',{p_name:name,p_kind:kind,p_scope:scope,p_justification:justification});return error?{ok:false as const,message:safeDatabaseMessage(error,'Não foi possível enviar a sugestão.')}:{ok:true as const,id:String(data)}}
 async mine(){const {data,error}=await this.client.rpc('my_taxonomy_proposals',{p_limit:100,p_offset:0});return error?{ok:false as const,message:safeDatabaseMessage(error,'Não foi possível carregar suas sugestões.')}:{ok:true as const,data:(data??[]).map(proposal)}}
 async queue(){const {data,error}=await this.client.rpc('taxonomy_moderation_queue',{p_limit:100,p_offset:0});return error?{ok:false as const,message:safeDatabaseMessage(error,'Não foi possível carregar a fila.')}:{ok:true as const,data:(data??[]).map(proposal)}}
 async review(id:string,decision:'approved'|'rejected',reason=''){const {error}=await this.client.rpc('review_taxonomy_proposal',{p_proposal_id:id,p_decision:decision,p_reason:reason||null});return error?{ok:false as const,message:safeDatabaseMessage(error,'Não foi possível revisar a sugestão.')}:{ok:true as const}}
}
export const TaxonomyRepository=supabaseClient?new SupabaseTaxonomyRepository(supabaseClient):null;
